### ISSUE TITLE
Captions and Subtitles - terminology

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#10]
Issue:
* Some areas use "captions" and "subtitles" _(subtitles only for translation)_.
* Some areas use "intralingual subtitles" _(same thing as "captions")_ and "interlingual subtitles" _(translations)_. 

**Straw proposal:**
* On the intro page, in the element list, use:
> **Captions/Subtitles** — Captions (also called “intralingual subtitles”)...
* For the page title and nav, use:
> **Captions/Subtitles**
* Explain the terminology in this [Captions and Subtitles section](https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/captions/#captions-and-subtitles)
* Primarily use "captions" (not "subtitles") throughout the resource.

**Rationale:**
* People who use only subtitle terminology will see "Captions/Subtitles" in the element description, navigation item, and page title &mdash; and hopefully easily make the connection.
* People who use captions and subtitles as different things, won't get confused.

**Comment by bakkenb** [comment]
+1 to straw proposal

**Comment by eoncins** [comment]
+1 to straw proposal

**Comment by eoncins** [comment]
I would avoid the use of the term "intralingual subtitles" and "interlingual subtitles" without a previous explanation, it may be considered jargon.
Maybe it is better to use the term "Subtitles for the Deaf and hard-of-hearing (SDH) for "intralingual subtitles" and "subtitles" for "interlingual subtitles".
According to De Linde and Kay (1999:1) “there are two distinct types of subtitling: intralingual subtitling (for the deaf and hard-of-hearing) and interlingual subtitling (for foreign language films)”.

Linde, Zoe de & Kay, Neil (1999). "The Semiotics of Subtitling". Manchester: St. Jerome Publishing.

**Comment by shawna-slh** [comment]
> I would avoid the use of the term "intralingual subtitles" and "interlingual subtitles" without a previous explanation, it may be considered jargon. Maybe it is better to use the term "Subtitles for the Deaf and hard-of-hearing (SDH) ...

We have it explained in the Captions/Subtitles page in this section: [Captions and Subtitles section]https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/captions/#captions-and-subtitles

On the intro page, in [Elements of Accessible Video and Audio Media](https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/#elements-of-accessible-video-and-audio-media), we currently have:

> **Captions/Subtitles** — Captions (also called “intralingual subtitles”) provide content to people who are Deaf and others who cannot hear the audio. Captions are a text version of the speech and non-speech audio information needed to understand the content. Subtitles are the spoken audio translated into another language.

I'm thinking that's OK because we have the explanation of it right there. I think it would be unnecessarily redundant to say: "Captions (also called subtitles for the Deaf and hard-of-hearing (SDH)) provide content to people who are Deaf and others who cannot hear the audio."

**Comment by sharronrush** [comment]
+1 to straw proposal

**Comment by eoncins** [comment]
+1 straw proposal

I also think that is important to align terminology with WCAG and avoid the use of different terms.

**Comment by cochfarf** [comment]
+1 to straw proposal

**Comment by shawna-slh** [comment]
done :-)
