### ISSUE TITLE
[ED - need not respond] [Planning] Reverse order in introduction

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-media-guide#104]
[low-medium]

> What accessibility features you provide with your media will likely be influenced by:
> 
> - governmental regulations and other policy requirements
> - budget and time constraints
> - user needs

Wondering about if this order should be reversed. Would like us to emphasize that what influences what is provided to make media accessible is mostly to meet the needs of users first and foremost.

Just an opinion. Take or leave it.

**Comment by shawna-slh** [comment]
Yes, user needs should be first! (Sylvie also commented on that a while ago and I thought I had changed it. Should be done now.)
