### ISSUE TITLE
[!!] [URL typo] [Planning]

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-media-guide#105]
Bottom of page, More about Standards section.
URL for "1.4.2 Audio Control (Level A)" has an extra "L" at the end giving a page not found error.

Also I noticed that up a bit in the "Pre-Recorded" table URLs, there was some inconsistency with which Understanding document 1.2.8 was going to in the various links for it.

**Comment by shawna-slh** [comment]
fixed. thanks!
