### ISSUE TITLE
[ED] [Response not needed] [Audio Content Video Content] Speaking Clearly

### ISSUE THREAD

**Issue by bakkenb** [w3c/wai-media-guide#106]
In this section...

> Speak clearly and slowly – speakers
> Speak clearly. Speak as slowly as appropriate. This will enable listeners to understand better, and make the timing better for captions and sign language.

We can give another reason in addition to what is there. "This will also avoid having inaudible audio that cannot be captioned by an external vendor." (or something similar)

Another reason why we stress it in our Pearson training recordings is that audio content that is not very clear will sometimes get kicked back to us by the captioning vendor as inaudible content and they won't caption it. Other vendors will actually put in the caption transcript the word "inaudible," so that it is not left blank when someone is reading the caption. They often have a human follow-up on the automated caption work, but sometimes _they_ can't even distinguish what is being said.

If it is not clear, the vendor may not be able to caption it in its entirety.

**Comment by shawna-slh** [comment]
added: "This is important for people wanting to understand the content, and for captioners."

> Speak clearly and slowly – _speakers_
> Speak clearly. This is important for people wanting to understand the content, and for captioners.
> Speak as slowly as appropriate. This will enable listeners to understand better, and make the timing better for captions and sign language.
