### ISSUE TITLE
Media Player Comparison Table is out of date

### ISSUE THREAD

**Issue by terrill** [w3c/wai-media-guide#108]
On the [Media Players](https://wai-media-guide.netlify.com/design-develop/media/player/) page, under the "Existing Players" heading, there is a link to a [Web-Based Media Player Accessibility Comparison Table](http://kensgists.github.io/apt/).  This resource is [maintained on Github](https://github.com/kensgists/apt), and it hasn't been updated since July 2016. 

I suspect @kensgists would welcome handing it off to someone else to update and maintain if W3C could help identify someone. It's a great resource, but only if it's reasonably up-to-date.

**Comment by shawna-slh** [comment]
Agree that is an issue. Do you know of a more up-to-date, comprehensive, vendor-neutral listing? If not, we were thinking that this one is better than nothing -- and maybe someone would step up to help provide updated info.

We have on EOWG's "wishlist" to take that on ourselves, but we don't have resources to do that for the foreseeable future.

For now, I added: "_(last updated July 2016)_"

Closing this issue for now, feel free to re-open if you have more input.

**Comment by kensgists** [comment]
Happy to hand this off, if someone wants to update it. Maybe, Terry, you have an intern who could update it?

Please let me know.
