### ISSUE TITLE
Include playback rate among user needs?

### ISSUE THREAD

**Issue by terrill** [w3c/wai-media-guide#109]
I recommend adding an item to this effect: 

> Some people have **difficulty processing** audio and video content at its default playback rate, and benefit from having the ability to either **slow down or speed up** the content.  

This need is described in the Media Accessibility User Requirements under [3.3. Time-scale modification](https://www.w3.org/TR/media-accessibility-reqs/#h-time-scale-modification).

**Comment by shawna-slh** [comment]
Thanks for the review and comment, Terrill!

We're not including all of the user needs in that section. It's already very long. My feeling is that this is not worth adding to the length.

We do have at https://wai-media-guide.netlify.com/design-develop/media/player/#player-accessibility-functionality :

> Some media players provide additional accessibility functionality to users such as:
> * Changing the speed of the video

I'm closing this issue for now. If you would like EOWG to reconsider and discuss it, feel free to re-open the issue.

**Comment by shawna-slh** [comment]
We do link to MAUR under that list:
> More information is in separate pages: [How People with Disabilities Use the Web](url) and [Media Accessibility User Requirements](https://www.w3.org/TR/media-accessibility-reqs/).

and also on the player page:
> More details on player accessibility functionality are in a separate document: [Media Accessibility User Requirements](https://www.w3.org/TR/media-accessibility-reqs/).
