### ISSUE TITLE
typo in summary on Planning page

### ISSUE THREAD

**Issue by terrill** [w3c/wai-media-guide#110]
The first bullet in the Summary o the [Planning Audio and Video Media](https://wai-media-guide.netlify.com/design-develop/media/planning/) page says this: 

> **figure out what your specific audio or video needs** (captions, description, a transcript, etc.)

Possible solutions: 

1. Add the word "are" after the word "needs" 
2. Remove the word "what" 
3. Express differently, maybe "Determine your specific audio or video needs"

**Comment by shawna-slh** [comment]
Hum, that wording works for me as a shorter way of saying:
> figure out what THINGS your specific audio or video needs (captions, description, a transcript, etc.)

Yet you are at least the second person to note it, so clearly it doesn't work for others. :-)

Thank you for the including possible solutions.

Would this wording work:
> figure out what your specific audio or video needs to be accessible (captions, description, a transcript, etc.)

@vmmiller what do you think?

**Comment by vmmiller** [comment]
Yes, that works, Shawn!

**Comment by shawna-slh** [comment]
Change made. Closing this issue. (Re-open if needed.)

**Comment by terrill** [comment]
My reaction to the original language - I now realize - was because I was perceiving "needs" to be a noun, whereas you're intending it to be perceived as a verb. If it's a noun, the new version still has the same problem - it seems to be missing a verb.

**Comment by shawna-slh** [comment]
> figure out what you need to provide for your specific audio or video (captions, description, a transcript, etc.)

seems overly wordy -- but maybe better, clearer... ?

**Comment by bakkenb** [comment]
Still not clear. How about...

> figure out what your specific audio or video needs in order to be accessible (captions, description, a transcript, etc.)

**Comment by terrill** [comment]
I like the addition of "in order to be accessible" - somehow that helps me to recognize "needs" as a verb.  Is "specific" necessary? It's a little shorter without it. 

> figure out what your audio or video needs in order to be accessible (captions, descriptions, a transcript, etc.)

**Comment by shawna-slh** [comment]
The editor in me reacts to "in order" as unnecessarily wordy. :-( And even "to be accessible" is unnecessary given the context.

Based on earlier exchange with Vicki, we edited a parallel version of that sentence in the [Intro page](https://wai-media-guide.netlify.com/design-develop/media/#how-to-make-audio-and-video-accessible) to
> To figure out which accessibility aspects your specific audio or video needs...

So I'll go with that on the Planning page, too.

**Comment by bakkenb** [comment]
+1 to that.
