### ISSUE TITLE
[before publication] media player in nav - move under "Audio Content & Video Content" ?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#112]
Shadi @nitedog said:
> [ED-med] Intro page, How to Make Audio and Video Accessible: I would prefer the paragraph on "Media Players" to be last, so that the page links are in order of the navigation.

**Comment by shawna-slh** [comment]
I'm changing my mind and will updat ethis...

<del>
We did have Media Players last in an iteration many weeks ago, and it made the section more complex. ([new preview so you can see it](https://deploy-preview-113--wai-media-guide.netlify.com/design-develop/media/#how-to-make-audio-and-video-accessible))

Of mild consideration is that the secondary navigation is not visible when reading that section.

In the Checklists at https://wai-media-guide.netlify.com/design-develop/media/planning/#checklist , we moved the media player up.

So maybe we should move the Media Player up in the navigation?

Personally I like it at the end, yet I don't feel super strongly and am OK with moving it if EOWG wants to.
</del>

**Comment by slhenry** [comment]
Here it alternative nav with:
Audio & Video Media
- Planning
- Audio Content & Video Content
- Media Player
- Description
- Captions/Subtitles
- Transcripts
- Transcribing Audio to Text
- Sign Languages

(I mildly don't like Sign Languages as the last item.)
