### ISSUE TITLE
[BEFORE publishing] URLs

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#115]
Sorry that I didn’t notice it before, sometimes you look at something and you can’t see it.

Currently the URLs are supposed to be pointing to

```
https://www.w3.org/WAI/design-develop/media/ …
```

Now, while I think in the navigation it makes sense to have the Guide under “Design & Develop”, it also has planning and content in it. As we can be flexible with our navigation and move resources as we want to, we are usually inclined to have URLs stay the same.

Also, I think we could have an easier to remember URL, too, by just using:

```
https://www.w3.org/WAI/media/ …
```

If I’m missing something, feel free to close this issue without comment :-D

**Comment by shawna-slh** [comment]
thank you, thank you, thank you for this! I totally agree!

I'll check with JB... (as we are supposed to ask her before creating new /WAI/@@ :-)

**Comment by yatil** [comment]
👍

**Comment by shawna-slh** [comment]
/media/av/
