### ISSUE TITLE
add guidance on creating separate audio track for speech, background, etc.?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#120]
From [e-mail](https://lists.w3.org/Archives/Public/wai-eo-editors/2019Sep/0057.html):

"
I am responding to the New Resource: Making Audio and Video Media Accessible.

In my experience, the biggest complaint users have over properly-caption video is that voices are obscured by other sounds, such as background music.

Unless I have missed it, there should presumably be a requirement for a standard multi-audio-channel format that separates sound into pre-designated categories, like voice | background music | effects and so forth, so that the viewer-listener can select different volume levels (or mute) each audio channel separately.

This can be done in many computer/video games today.
"

**Comment by shawna-slh** [comment]
[e-mail reply](https://lists.w3.org/Archives/Public/wai-eo-editors/2019Sep/0059.html):

"
Thank you for your feedback related to making audio and video accessible. It's useful to get your perspective on the biggest complaint users have.

There is a requirement in WCAG for "Low or No Background Audio" and we include that in the new resource:
* https://www.w3.org/WAI/WCAG21/Understanding/low-or-no-background-audio.html
* https://www.w3.org/WAI/media/av/av-content/#use-low-background-audio--recording-post-production-wcag-aaa

A different resource, "Media Accessibility User Requirements", covers separate volume controls for multiple audio channels under "clean audio" at:
* https://www.w3.org/TR/media-accessibility-reqs/#clean-audio

I don't know of media players that support that now. Do you? (It's good to know that many games do.) It would be good to know if media player developers have this on the their list for future development.

The "Making Audio and Video Media Accessible" resource we wanted to keep practical with functionality that is available today. If media players aren't going to support it in the foreseeable future, we probably don't want to add it to the resource. Although, we might want to mention it so that people developing audio and videos can prepare separate tracks so they are available in the future when media players do support it.

I created a GitHub issue to collect additional input:
	https://github.com/w3c/wai-media-guide/issues/120

For now, I've got this as low priority. I will keep it "on my radar" for input on making it higher priority to consider adding to the resource.

[ Side note: This chicken-and-egg issue is addressed in https://www.w3.org/WAI/fundamentals/components/ "If an accessibility feature is not implemented in one component, there is little motivation for the other components to implement it when it does not result in an accessible user experience." ]

Thanks again for your input!

"

**Comment by shawna-slh** [comment]
ping @terrill in case you have any input from the media player perspective :-)

**Comment by sleepingdog** [comment]
Thanks. I remember reading about Clean Audio but it seems not to have taken off. I think there are some multi-channel-capable players, but not for the purposes of voice-audio-separation. The major source of the complaints I mentioned was for web-based videos in online learning (MOOC) courses, where the learners were often at or beyond retirement age. But it applies equally to any television content.

The point would be that users are likely to find a general volume-combination setting that suits them, perhaps setting voice at level 8/10, background music at 2, effects at 5; rather than have to keep fiddling with volume controls for every piece of video content.

The only observation I would make, then, is that it would be helpful to prepare and retain separate audio channels for voice, background music, effects and so forth, rather than flatten them and lose the separate sources, to provide for re-exporting video to a new multi-audio-channel (object based?) format. In other words, a future-proofing strategy.

**Comment by terrill** [comment]
Currently the only context in which Able Player has two audio tracks playing simultaneously is when audio description is delivered via a WebVTT file and read aloud by browsers via the Web Speech API. In that context, the audio description can be controlled by the computer's volume control, and the video's volume can be controlled separately with the media player volume control.  Able Player doesn't support separate audio tracks, nor is that on our roadmap. 

I'm intrigued by the idea of having multiple audio tracks and giving the user total control over the sound mix. The UI for something like that could be a mixer console with a separate volume slider for each track. I suspect that would be challenging for users though if tracks have fluctuating dynamics. Users would have to frequently be raising and lowering tracks as the content changes.

**Comment by shawna-slh** [comment]
The perspective of several EOWG participants is that (almost) no one will do this until it's supported. ([meeting minutes](https://www.w3.org/2020/10/30-eo-minutes#item04))

And, we don't want to add more information to the resource unless it will likely improve accessibility in the foreseeable future.

Therefore, EOWG agreed to leave it out for now and
**Keep it in mind to pay attention to, and add when/if tools support it.**

**Comment by shawna-slh** [comment]
Note that we do have:

> **Use low background audio**
> When the main audio is a person speaking and you have background music, set the levels so people with hearing or cognitive disabilities can easily distinguish the speaking from the background.
> Specifically, make the background sounds at least 20 decibels lower than the foreground speech content (with the exception of occasional sounds that last for only one or two seconds).
> Avoid sounds that can be distracting or irritating, such as some high pitches and repeating patterns.
> More information is in [Understanding Success Criterion 1.4.7: Low or No Background Audio (AAA)](https://www.w3.org/WAI/WCAG21/Understanding/low-or-no-background-audio.html).

in https://www.w3.org/WAI/media/av/av-content/#use-low-background-audio--recording-post-production-wcag-aaa
