### ISSUE TITLE
"live" and "pre-recorded" terminology

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#13]
From [Estel·la in e-mail](https://lists.w3.org/Archives/Public/wai-eo-editors/2019Jun/0002.html):

> Here is also a terminology issue.
> For "live" it can be called: "live", "realtime" or "on-line"
> For "pre-recorded" it can be called: "pre-prepared", "pre-recorded" or "off-line"

WCAG uses "live" and "prerecorded".  I'm currently thinking those terms will be fairly easily understood by people who are used to different terms, and we can just use the "**live**" and "**pre-recorded**" (added hyphen to make more understand for all, especially non-native speakers).

@eoncins and others: What do you think?

**Comment by sharronrush** [comment]
+1 to retaining "live" and "pre-recorded"

**Comment by nitedog** [comment]
+1 to keeping WCAG terminology for recognizability

**Comment by daniel-montalvo** [comment]
I also think we should keep WCAG terminology as much as we can. Maybe explaining these concepts for audiences who are not familiar with WCAG would be nice too.

**Comment by eoncins** [comment]
I also think that we should keep WCAG terminology.


I consider that it was worth to inform about the different terminology. Maybe these terms can be included in the meta data for search?


What do you think?


Best,


Estel·la


Edifici MRA 126  - Campus UAB
08193 Bellaterra
Barcelona
T. +34 610 655 149

orcid.org/0000-0002-0291-3036<https://orcid.org/0000-0002-0291-3036>
http://grupsderecerca.uab.cat/transmedia/
________________________________
De: daniel-montalvo <notifications@github.com>
Enviat el: dimarts, 11 de juny de 2019 16:53:41
Per a: w3c/wai-media-guide
A/c: Estel·la Oncins Noguer; Mention
Tema: Re: [w3c/wai-media-guide] "live" and "pre-recorded" terminology (#13)


I also think we should keep WCAG terminology as much as we can. Maybe explaining these concepts for audiences who are not familiar with WCAG would be nice too.

**Comment by cochfarf** [comment]
+1 to retaining "live" and "pre-recorded"

**Comment by shawna-slh** [comment]
> Maybe these terms can be included in the meta data for search?

Good to think about.

I *think*, but don't know, that adding these terms to meta data wouldn't impact search results much given current algorithms. I'd like to call this a low priority issue that we don't have time to address now.

If anyone disagrees, feel free to re-open the issue.

[update:] "live" and "realtime" are now included in the headings and text of the [Captions/Subtitles page](https://wai-media-guide.netlify.com/design-develop/media/captions/)
