### ISSUE TITLE
audio description - scope include movies & TV or not?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#14]
**We want to focus on web videos**, as opposed to things like movies and TV shows.

Question 1: Will what we include in the [Descripton page](https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/description/) apply to movies and TV, too?

Question 2: If we were to include in our scope movies and TV shows, would we provide much more or different information?

**If 1."no" and 2. "yes"**, then we probably want to note that what's in scope and out of scope. For example, with wording such as:
> This page addresses common types of videos designed for the web such as instructional videos, training videos, recordings of presentations, and such. It does not address all the issues around full-feature movies, television shows, and such.

_[update:]_ **If 1. "yes" and 2. "no"**, then maybe we don't need to say anything about scope?

@eoncins and others: Thoughts?

**Comment by sharronrush** [comment]
My inclination is to avoid discussion of movies, etc. The scope description is good. +1 to that option.

**Comment by nitedog** [comment]
I'm not sure the guidance would be any different for movies and TV shows, and would recommend to keep them in scope. Things like identifying who is speaking etc. applies to an instructional video just as well.

Having said that, we need to exclude *broadcasting* (ie. non-web transmission of media content) from the scope. I think the current definition addresses this well.

**Comment by daniel-montalvo** [comment]
+1 to not specifically exclude TV and movies but to exclude broadcasting and non-web transmissions.

**Comment by eoncins** [comment]
+1 to not specifically exclude TV and movies but to exclude broadcasting and non-web transmissions.


Agree with Shadi that guidance for web videos would be the same as for movies and TV shows.

I understand that the guidance is for users to produce their own audio descriptions.


The problem that I see is indie productions for full-features and advertising which are uploaded in YouTube and Vimeo and more recently in Facebook, Twitter and Instagram to name the major video-sharing platforms. Are we approaching all content provided in these platforms? Do we want to approach all content provided in these platforms?


Also all broadcasters are being forced to move more and more to the web and most of them offer on-demand services. Are we approaching them? Should we approach them?


A particular issue are public administrations with their own web channels like Parliaments. Are we approaching these administrations?


Sorry these are only some thoughts that I think that are relevant to take into consideration.


Best regards,


Estel·la



Edifici MRA 126  - Campus UAB
08193 Bellaterra
Barcelona
T. +34 610 655 149

orcid.org/0000-0002-0291-3036<https://orcid.org/0000-0002-0291-3036>
http://grupsderecerca.uab.cat/transmedia/
________________________________
De: daniel-montalvo <notifications@github.com>
Enviat el: dimarts, 11 de juny de 2019 16:48:30
Per a: w3c/wai-media-guide
A/c: Estel·la Oncins Noguer; Mention
Tema: Re: [w3c/wai-media-guide] audio description - scope include movies & TV or not? (#14)


+1 to not specifically exclude TV and movies but to exclude broadcasting and non-web transmissions.

**Comment by cochfarf** [comment]
+1 to not specifically exclude TV and movies but to exclude broadcasting and non-web transmissions.
I think the information for creating descriptions for movies could be different than for web videos so that may need to be addressed somewhere.

**Comment by shawna-slh** [comment]
I deleted the scope paragraph. If when we're looking at it in detail we think we need to add that broadcasting is out of scope, we can. At this point, I think given the context around the resource, it would be unnecessary clutter. Happy to revisit later if warranted.

**Comment by shawna-slh** [comment]
@eoncins Thank you for your thoughtful input.

When you say "Are we approaching them?" - do you mean:
1. Are they target audience for this resource?
or
2. Will we actively reach out to them with this information?

The answer to 1 is yes. I added a bullet to [Scenario / Use Case Examples](https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#Scenario_.2F_Use_Case_Examples) Let me know if you think we need more there.

For 2, we will define an "outreach plan" for promoting this resource. I expect that we will invite people to reach out to these audiences, although we might not have resources to do much.

Does that answer your questions?

**Comment by eoncins** [comment]
Thanks for the replay Shawn.


My question was 1 and agree with the information provided in Scenario/Use Case Examples.


Edifici MRA 126  - Campus UAB
08193 Bellaterra
Barcelona
T. +34 610 655 149

orcid.org/0000-0002-0291-3036<https://orcid.org/0000-0002-0291-3036>
http://grupsderecerca.uab.cat/transmedia/
________________________________
De: shawn_slh <notifications@github.com>
Enviat el: dimarts, 18 de juny de 2019 18:30:46
Per a: w3c/wai-media-guide
A/c: Estel·la Oncins Noguer; Mention
Tema: Re: [w3c/wai-media-guide] audio description - scope include movies & TV or not? (#14)


@eoncins<https://github.com/eoncins> Thank you for your thoughtful input.

When you say "Are we approaching them?" - do you mean:

  1.  Are they target audience for this document?
or
  2.  Will we actively reach out to them with this information?

The answer to 1 is yes. I added a bullet to Scenario / Use Case Examples<https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#Scenario_.2F_Use_Case_Examples> Let me know if you think we need more there.

For 2, we will define an "outreach plan" for promoting this resource. I expect that we will invite people to reach out to these audiences, although we might not have resources to do much.

Does that answer your questions?
