### ISSUE TITLE
[low] [automatic captions example] image alt or not?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#146]
Under [Automatic Captions are Not Sufficient](https://www.w3.org/WAI/media/av/captions/#automatic-captions-are-not-sufficient)

we have this text:
>  Example of bad automatic captions (that cause a fire)
> Spoken text:
> "Broil on high for 4 to 5 minutes. You should not preheat the oven."
> Automatic caption:
> "Broil on high for 45 minutes. You should know to preheat the oven."

We didn't put alt on the image, as it's not needed to understand the content.

Yet, I'm occasionally tempted to suggest adding:
`alt="food on fire under broiler" `

**Comment by bruce-usab** [comment]
Please do add the alt!  The picture is more than mere decoration!

I sent this around the office, it is so timely.  Happy Thanksgiving!

**Comment by shawna-slh** [comment]
I think since "(that cause a fire)" is there, then the alt is not *needed*.
Yet, it does add a bit to the impact of the example.

Done. (will be published with a few other updates later today)
