### ISSUE TITLE
[Sign Language] Alternative Text is missing

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#170]
I think it would be beneficial to describe a good practice button in the alternative text of the button illustration. I was wondering what “[Auslan](https://en.wikipedia.org/wiki/Auslan)” (text on the button) was referring to and had hoped to gain more insight from the alternative text. 

I had not consciously heard “Auslan” as a reference to _Australian Sign Language_ before, and it doesn’t help that the word is so close to the German word “Ausland” – abroad – so the illustration was not really illustrative to me.

![Screenshot of the bullet point with the missing alternative text](https://user-images.githubusercontent.com/58862/111965862-83a2bb00-8af6-11eb-9f2a-092681f245c8.png)

**Comment by shawna-slh** [comment]
done https://github.com/w3c/wai-media-guide/pull/171/commits/95daf76a000826ba111081ae32862269973b2ef0
