### ISSUE TITLE
[Important] planning page: indicate Level AA assumption

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#21]
Under the "what does my audio/video need", there is an implicit assumption of WCAG Level AA when we differentiate between required and optional (marked as "ideally"). In some jurisdictions there are other (higher) requirements (eg. sign language on some types of pages in Germany). Please indicate the underlying assumption for differentiating required and optional.

**Comment by shawna-slh** [comment]
Yup. Done in [Planning](https://wai-media-guide.netlify.com/design-develop/media/planning/). (totally revised it - adding A, AA, AAA -- and put more info in an Introduction).

Will do in others as well. :-)
