### ISSUE TITLE
Media Player - list WCAG SCs that apply?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#24]
[Accessible Media Player - draft page](https://wai-media-guide.netlify.com/design-develop/media/player/)

**Comment by bakkenb** [comment]
I think so (in my opinion), but good question.
Would it only be 1.2.2? Since audio descriptions, ASL and other stuff are not "controlled" by the actual player? Only Captions are controlled by the player?

**Comment by shawna-slh** [comment]
If people are coding their own player, there is a *lot* they need to consider. I added several in [Player Accessibility Functionality](https://wai-media-guide.netlify.com/design-develop/media/player/#player-accessibility-functionality)

Feel free to re-open if you think of others.
