### ISSUE TITLE
[word-smith-level] "Understanding User Needs" or "Understanding User Experiences"

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#26]
[Intro page](https://wai-media-guide.netlify.com/design-develop/media/) first section title ideas:

1. Understanding User Experiences
2. Understanding User Needs

reasons for or against?

other suggestions?

**Comment by shawna-slh** [comment]
> 1. Understanding User Experiences

for: "user experience" is **positive**, common terminology

> 2. Understanding User Needs

for: "needs" strongly communicates that people **_need_** these things &mdash; they're not just nice-to-have
against: "needy" has **negative** connotations

**Comment by bakkenb** [comment]
+1 to "Understanding User Needs"
Rationale - The content reads more to the need of various people with disabilities rather than their experience when accessing inaccessible media content.

**Comment by shawna-slh** [comment]
> Rationale - The content reads more to the need of various people with disabilities rather than their experience when accessing inaccessible media content.

Interesting how you read it.

I was trying to show positive **user experiences with _accessible_** media! :-)

> * Many people who are Deaf can read text well, and use transcripts or captions. Some cannot, and prefer sign language.
> * Many people who are hard of hearing like to listen to the audio to hear what they can, and have captions to fill in what they can’t hear adequately.
> * Some people who have difficulty processing auditory information also use captions. ...

Maybe want to tweak it even more that way?

**Comment by bakkenb** [comment]
My feeling of that it reads more like "needs" is from bullets 3, 4, and 5 I guess as it specifically says "need" in them.

> - Some people who have difficulty processing auditory information also use captions. Many need transcripts so they can read at their own pace.
> - People who are blind need to know the relevant visual information in a video. Audio description of visual information can be provided separate from the main video.
> - People who are Deaf-blind need the audio information and the visual information in text so they can read it with Braille. They need descriptive transcripts.

Okay with leaving or re-writing. It just seems that the title "Understanding User Needs" fits better if it is not re-written. [medium- but okay with ED]

**Comment by eoncins** [comment]
+1 to "Understanding User Needs"

**Comment by cochfarf** [comment]
+1 to "Understanding User Needs"

**Comment by yatil** [comment]
No preference.

**Comment by yatil** [comment]
In the tutorials, this section is called ”Why is this important” and includes “Additional benefits” as well.
