### ISSUE TITLE
[minor question] other benefits examples

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#27]
In [Additional Benefits](https://wai-media-guide.netlify.com/design-develop/media/#additional-benefits) section:

> ... captions can be:
> * Used in loud environments where users cannot hear the audio. For example, a bar, an airport, and [@@ another good example].
> * Used in quiet environments where users cannot turn on sound. For example, a library, when others are sleeping, and and [@@ another good example].

Ideas for other examples? :-)

**Comment by eoncins** [comment]
- For loud environments maybe also large venues when distance to the speaker is too big
- For quiet environments maybe also workplace 
Additional benefits:
- Sound is not available (e.g., muted, no working speakers)
- Persons  who  need  the  content  to  be  in  another  language

**Comment by yatil** [comment]
* In public transport (kinda both – it can be a loud environment, so captions help understanding and on the other side it is not expected to have sound blasting from your phone there).
