### ISSUE TITLE
Caption display control

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#28]
I'm thinking about display of captions &mdash; things like font family, text size, text color, background color, etc. What do we want to include about that and on what page? (For example, if it's mostly in the coding with the media player, then we'd include in on the media player page and point to that from the captions page.)

**Question: How much control do authors/designers/coders have in how captions are displayed by default in browser-default-players and in players designed for accessibility such as AblePlayer?** (If little control, then we won't say much.)

**Comment by eoncins** [comment]
Agree.
Only in the case of burn-in subtitles for pre-recorded media the author can decide font, size, background and position.

**Comment by shawna-slh** [comment]
[From Estel·la](https://github.com/w3c/wai-media-guide/issues/12#issuecomment-510690602)

> It is true that most of the times it depends on the video player. In fact, it also depends if the subtitle/captions are an extra file (.WebVTT or .srt) or if they are burn-in.

> For instance in YouTube the users can adapt the subtitles/captions to their needs "https://support.google.com/youtube/answer/100078" because the player allows them to do so if captions/subtitles are available.

> However, if the subtitles are burn-in then font, size and background has to be taken in consideration.

> In the case of live captions there are different platforms which can be used as secondary screens that allow end user to select their preferences in terms of font, size and background.

**Comment by yatil** [comment]
I think we need to strongly suggest closed captions (so not-burned-in) and leaving the settings to the user. Most media players who have captions support seem to have decent caption styling.

**Comment by shawna-slh** [comment]
Thanks for the input @eoncins & @yatil !
