### ISSUE TITLE
Level of detail to include and links to outside resources

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#30]
## Important Background

EOWG is very cautious about linking outside of W3C. There are several reason including:
* Not wanting to appear to show preference for one resource over another, especially if from a for-profit company. Not wanting to be asked to link to a different resource, and be in an awkward situation if we don't want to for some reason.
* Not wanting the maintenance of monitoring for changing links or changing content.

We sometimes do link to outside resources.

Below are some situations where we might want to.

We will discuss these in the 19 July meeting.

**UPDATE:**
* [x] checkboxes below indicate updates based on [EOWG input in 19 July meeting](https://www.w3.org/2019/07/19-eo-minutes.html#item05)

## 1. Links to guidance elsewhere

1.1. In [Description page, Tips for Writing Descriptions section](https://wai-media-guide.netlify.com/design-develop/media/description/#writing):
> More guidance on writing descriptions: [Description Tip Sheet [icon]]( https://dcmp.org/learn/227) and [How to Describe [icon]]( http://www.descriptionkey.org/how_to_describe.html).

* [x] Left level of content and links.
* [x] Changed text to say more on web, these just some:
> More guidance on writing descriptions is available on the web, for example: ...

1.2. In [Sign Languages page, Creating Sign Language Alternatives](https://wai-media-guide.netlify.com/design-develop/media/sign-languages/#creating-sign-language-alternatives):
> There are resources on the web that provide guidance on creating sign language alternatives. For example:
> * [Sign Language Interpretation in HBBTV (PDF)](http://pagines.uab.cat/hbb4all/sites/pagines.uab.cat.hbb4all/files/sign_language_interpreting_in_hbbtv.pdf) includes specific guidance on aspects such as:
>    * sign language interpreters
>    * filming the signing
>    * position of the sign language
> * Guidelines for the Production of Signing Books:
>    * [Sign language presentation](http://www.sign-lang.uni-hamburg.de/signingbooks/deliver/d31/deliv_31_part3-2.html#3.2.2.6)
>    * [Filming the signers](http://www.sign-lang.uni-hamburg.de/signingbooks/sbrc/grid/d71/guide12.htm)
>    * [Editing](http://www.sign-lang.uni-hamburg.de/signingbooks/sbrc/grid/d71/guide13.htm)

* [x] Added some specific guidance
* [x] Leave links, edited them down (since included more in this page)

1.3. In [Transcribing Audio to Text page, How to Transcribe section](https://wai-media-guide.netlify.com/design-develop/media/transcribing/#how-to-transcribe):
> More details on options and tools for transcribing are in: Transcripts on the Web, [How to get or make transcripts [icon]]( http://www.uiaccess.com/transcripts/transcripts_on_the_web.html#justdoit).

* [x] leave level of content and links as is
* [x] got linked resource updated to 2.1

## 2. Links to YouTube and AblePlayer

Rationales:
* YouTube is likely the thing that most people will use, especially do-it-yourself-ers.
* AblePlayer is the most accessible free player that we know of.

2.1. In [Captions page, automatic captions section](https://wai-media-guide.netlify.com/design-develop/media/captions/#automatic-captions-are-not-sufficient):
> There are tools that use speech recognition technology to turn a soundtrack into a timed caption file. For example, many videos uploaded to YouTube have automatic captions. ([YouTube info]( https://support.google.com/youtube/answer/3038280))

* [x] Changed sentence to "For example, some common video websites provide automatic captions."
* [x] deleted link

2.2. In [Captions page, Captions Tools section](https://wai-media-guide.netlify.com/design-develop/media/captions/#caption-tools):
> Some tools create automatic captions that you can use as a starting point. For example, YouTube provides automatic captions and tools for you to edit the captions, as described in [Edit or remove captions – YouTube Help]( https://support.google.com/youtube/answer/2734705?hl=en). You will need to edit automatic captions for accuracy.

* [x] Change sentence to "Several free and fee-based tools create automatic captions that you can use as a starting point. For example, a common video website includes automatic captions and tools for you to edit the captions."
* [x] deleted link

2.3. In [Accessible Media Players page, Existing Players section]( https://wai-media-guide.netlify.com/design-develop/media/player/#existing-players):
> Each media player provides documentation of the steps to set it up in a web page. For example [AblePlayer Setup Steps]( https://wai-media-guide.netlify.com/design-develop/media/player/setup-step-1-use-html5-doctype).

* [x] left as is

## 3. Other links

3.1. In [Sign Languages page, Example section](https://wai-media-guide.netlify.com/design-develop/media/sign-languages/#example):
> Example sign language in video: [NHS 111 British Sign Language (BSL) Advert (YouTube)]( https://www.youtube.com/watch?v=TCq3ru9HQSc)

* [x] left as is

3.2. In [Accessible Media Players page, Existing Players section]( https://wai-media-guide.netlify.com/design-develop/media/player/#existing-players):
> The following resources list accessibility support in several media players: [Media Player Accessibility Comparisons]( https://docs.google.com/spreadsheets/d/1QJVcXx5hTWYBcJbHJD3DrL3hSFVbfy1VQFyADMtrDFY/edit?pli=1#gid=0) and [Web-Based Media Player Accessibility Comparison Table]( http://kensgists.github.io/apt/). (At the time of this writing, these resources had data from 2014 or 2016, and may be out of date.)

_([related issue](https://github.com/w3c/wai-media-guide/issues/51))_

* [x] Changed to:
> There is information online indicating the accessibility of media players. For example, [Web-Based Media Player Accessibility Comparison Table [offsite icon]](http://kensgists.github.io/apt/).

3.3. In [Intro page, Additional Benefits section]( https://wai-media-guide.netlify.com/design-develop/media/#additional-benefits):
> @@ link to [National Research Study: Student Uses and Perceptions of Closed Captions & Transcripts](https://www.3playmedia.com/resources/industry-studies/student-uses-of-closed-captions-and-transcripts/)

* [X] included as:
> To better understand content because users can hear the information in audio and see it in text at the same time. For example, a [Research Study of Closed Captions & Transcripts](https://www.3playmedia.com/2019/02/21/8-benefits-of-transcribing-captioning-videos/) found that 71% of students _without_ hearing difficulties use captions, primarily to help them focus and retain information.

**Comment by yatil** [comment]
(not strongly)
I don’t feel terrifically good pointing to YouTube as a de-facto standard. With the HTML video element, it is possible for everyone to host locally instead of using YouTube. Many other services also provide automatic captions and ways to edit them, for example [Trint](https://trint.com).

**Comment by shawna-slh** [comment]
> (not strongly)
I don’t feel terrifically good pointing to YouTube as a de-facto standard. With the HTML video element, it is possible for everyone to host locally instead of using YouTube. Many other services also provide automatic captions and ways to edit them, for example Trint.

based on [EOWG input from 29 July](https://www.w3.org/2019/07/19-eo-minutes.html#item05) and additional research, removed links to YouTube and replaced text - per above

**Comment by shawna-slh** [comment]
phew - finally got through them all!
