### ISSUE TITLE
[Planning page] Video Checklist - player first

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-media-guide#33]
In the video checklist - put accessible media player as the first check box, and then have the yes/no statements.  First and foremost, you need an accessible media player to play content.   I think its buried at the bottom of the checklist.

**Comment by shawna-slh** [comment]
To see it in context: [Planning page, Video Checklists](https://wai-media-guide.netlify.com/design-develop/media/planning/#video-checklist)

**Comment by yatil** [comment]
+1 – I think that makes sense.

**Comment by shawna-slh** [comment]
Pulled out into [separate section](https://wai-media-guide.netlify.com/design-develop/media/planning/#checklists-for-audio-and-video), as decided in [19 July EOWG telecon](https://www.w3.org/2019/07/19-eo-minutes.html) topic with Kris Anne & Eric.
