### ISSUE TITLE
[Planning] Standards its own page?

### ISSUE THREAD

**Issue by kakinney** [w3c/wai-media-guide#34]
Having the standards listed at the bottom of the planning page felt disjointed to me.  I feel like they should be listed on the introduction page, or have their own separate page.  if they have a separate page, I would list it as:

1. Introduction
2. Standards
3. Planning
4. All the techniques to meet those standards as they are listed.

**Comment by shawna-slh** [comment]
Yeah, where to put standards was a tough one! Back in April and early May, we tried several options, including:
* [on the intro page](@))
* [on a page with "standards" in the title](https://deploy-preview-1--wai-media-guide.netlify.com/design-develop/media-guide/managing-standards/)
* [on a totally different page](https://deploy-preview-6--wai-media-guide.netlify.com/design-develop/media-guide/together/)

When making the final decision on organization in May, we thought more about the [Tasks in the Requirements Analysis]( https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#Tasks).

We actually do ***not*** want this *practical-guidance-for-getting-it-done resource* to have emphasis on standards. For example, see the Tutorials (e.g., [labeling controls]( https://www.w3.org/WAI/tutorials/forms/labels/)), where standards are only mentioned at the bottom of relevant pages.

Throughout the resource, I have added links to that standards section, so readers can get there when they need to.

Are you OK going with the EOWG's previous decision and leaving Standards where it is?

**Comment by yatil** [comment]
(editor’s discretion)
I am ok with leaving it, but it is a substantial part (25%) of the resource. If we would use a tutorial-like info-box approach just listing SCs, we could have them contextually on the individual pages. However this seems a little bit excessive for planning. I have no better idea apart from using a separate page. And **I** _do not_ want to re-open this issue.

**Comment by shawna-slh** [comment]
We chose not to have the SCs on the individual pages because we deemed it more important to show the overall view of that is in WCAG.

> it is a substantial part (25%) of the resource

-> it is a substantial part (25%) of _this one page_ of the resource

> And I do not want to re-open this issue.

+1 from me :-)

Hopefully Kris Anne, too. :-)
