### ISSUE TITLE
(medium) [overview page] unusual reference to standards

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#36]
> * accessible to people with disabilities
> * meet international standards

I don't understand the need for separating "accessible" from "international standards". I'm aware that there are different levels of meeting the standard but the way this is phrase, it seems that meeting the standards is separate from being accessible. I disagree with this separation and for unnecessary complexity -- I think "make your audio and video media accessible to people with disabilities" is sufficient.

**Comment by shawna-slh** [comment]
deleted
