### ISSUE TITLE
(low) [overview page] move reference to Media Player page?

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#38]
I like how you are listing out the pages that provide overall considerations ("Planning" and new "Audio and Video Content"), and pages that describe specific features ("Audio Description", "Captions", "Transcripts", and "Sign Language"). Then the page "Media Player" kind of startled me. This is not really a feature but also an overall consideration, so why is it listed like that?

**Comment by shawna-slh** [comment]
It seemed right. :-) But happy to change. Done.
