### ISSUE TITLE
(high) [overview page] move example video into example section

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#39]
> An example accessible video is Video Captions. That page provides

The actual video is provided at the bottom of the page, somewhat out of context. I suggest that the video is included directly in the example section rather than at the bottom of the page.

Also the wording is somewhat confusing -- "an example video ... that page" -- maybe "an example video is provided on the video captions page" or such?

**Comment by shawna-slh** [comment]
+1 to wording clarification. I changed it to:
> An example accessible video is on the [Video Captions page](https://www.w3.org/WAI/perspective-videos/captions/). That page provides:

At the bottom of the page is just _a still image_ that is linked to the same page.

I considered embedding a video on this page -- along with player and all -- , but I think it would:
* add to the complexity of the page quite a bit
* be distracting and pull attention away from the other information

Feel free to re-open the issue if you disagree or want more consideration, e.g., from WG.

**Comment by nitedog** [comment]
1. I suggest using the same thumbnail approach to include the video, as you've done later on that page
2. I suggest using a different video for the example than the one at the bottom of the page
3. I wonder if the video at the bottom of the page should be placed higher up in that same section

**Comment by yatil** [comment]
I strongly support to showing different accessibility features instead of just telling the reader about it. So having them inline-ish or at least prominently linked would be good.

**Comment by shawna-slh** [comment]
> I strongly support to showing different accessibility features instead of just telling the reader about it. So having them inline-ish or at least prominently linked would be good.

I do not understand what you are suggesting.

**Comment by shawna-slh** [comment]
> 1. I suggest using the same thumbnail approach to include the video, as you've done later on that page

You mean just adding a thumbnail that is *linked*? Per above, it does not *include* the video in this page.

> 2. I suggest using a different video for the example than the one at the bottom of the page

Done.

> 3. I wonder if the video at the bottom of the page should be placed higher up in that same section

I think it's good at the bottom. If higher, I think many people would follow the link to the video and then not read the rest of the bullets.

Also, I like the visual anchor of the thumbnail at the bottom. 

**Comment by nitedog** [comment]
1. Yes, I think that adding a thumbnail helps indicate that this will lead to a video.
2. Great!
3. I feel it is a little "dangling" there (after I read all this you tell me that I could have viewed a 1-minute video?!) but I don't feel strongly about this. Maybe there is another way of highlighting the video? Up to editor...

**Comment by shawna-slh** [comment]
1. done.
3. Well, I had it higher up in the page under "Example" and you made me change it. ;-)

Would like to leave it as is and close this issue for now. Maybe I'll have change of perspective or we'll get other inspiration later.

**Comment by shawna-slh** [comment]
Looky! I figured out a smooth way to [put it higher](https://wai-media-guide.netlify.com/design-develop/media/#additional-benefits)!

**Comment by nitedog** [comment]
I knew you would!
