### ISSUE TITLE
(high) [Planning page] remove "minimum"

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#40]
> This resource endeavors to help you know the minimum requirements and encourages you to meet all user needs

I think that entire sentence is superfluous because you already repeat "minimum" in the very next section. At least remove the word "minimum" if you want to keep this sentence.

> * include all that is needed to meet user needs (including what goes beyond minimum accessibility standards and policies)

We don't know all policies to be able to say that. I don't think the text in brackets is needed, and seems to reinforce the "minimum" mindset.

**Comment by yatil** [comment]
Maybe basic would be a better word. We struggled with this for the tutorials. I don’t feel like readers benefit much by showing them where the line for the minimum compliance is and what is all optional (as that probably means it will be ignored). I think it is better to say “here are all the things you can do” and then give people the information (in the standards section/page) to find out what their minimum requirements are. (Or accidentally provide really good accessibility 😉)

**Comment by shawna-slh** [comment]
changes made - will upload when done with others.
