### ISSUE TITLE
(low) [Planning page] do not bold A/AA

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#42]
I suggest leaving out the bolding of A and AA levels in the checklists. It is up to the reader to decide which features and levels to emphasize.

**Comment by yatil** [comment]
(leave to the editor from my POV)

**Comment by shawna-slh** [comment]
hummm - realistically a lot of readers will be focused on doing the minimum that they need to do to meet WCAG 2 Level AA. **It seems bolding helps those readers.** (Tangentially, it also serves to visually and cognitively chunk the list a bit.)

Although, I really want to encourage descriptive transcripts, and that's at AAA. So leaving that bolded is editorializing probably more than we should.

I'll change the bolding. :-)
