### ISSUE TITLE
[LATER version] [Content page] consider note on pitch/patterns

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#46]
In "Use low background audio", consider a note that some particular audio pitches and patterns can be distracting and irritating, even when they are more than 20 decibels lower. This note may also be relevant to the section on seizures.

**Comment by shawna-slh** [comment]
Good point. However, it seems "some particular audio pitches and patterns can be distracting and irritating" is too vague to even be helpful.

Does anyone know of:
* more specific guidance we can give?
* resources with more info that we might want to point to?

**Comment by yatil** [comment]
I don’t think it is too vague, considering the other content on the page. I know that background audio can be a big problem for people with hearing issues and auditory processing disorder. Maybe we could say “If possible avoid high pitch noise or repeating sound patterns during narration and speech.”

(not strong, just brainstorming)

**Comment by shawna-slh** [comment]
Put this for now:

> Avoid sounds that can be distracting or irritating, such as some high pitches and repeating patterns.

Can edit later when better info is figured out.
