### ISSUE TITLE
(medium) [Content page] make destination of "see more" clearer

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#47]
> See more information in Audio Description of Visual Information.

It may make sense to clarify that this link goes to a section within the next page. Right now it is not very clear where this goes, and the relationship between this link and the one directly below to the next page.

**Comment by yatil** [comment]
(medium) Suggest removing the heading and link, I think it serves little value.

**Comment by shawna-slh** [comment]
@nitedog : Changed to:
> More information is in the next page of this resource: Audio Description of Visual Information.

@yatil : Readers might land on that page without any context, e.g., from a search engine. I think it's important to make it clear that there is more info available. Not everyone will see the links below or elsewhere.
