### ISSUE TITLE
(low) [Transcripts page] use of "we" and "minimum"?

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#49]
> We strongly recommend that you provide descriptive transcripts, even though they are not required to meet most minimum accessibility standards.

Same as issue #45 on use of "we" and issue #40 on use of "minimum"

**Comment by shawna-slh** [comment]
deleted.

**Comment by shawna-slh** [comment]
fyi, I found a few more instances of "minimum" and deleted them. Will keep on the look out for more. Feel free to let me know if you find any before I do. :_)
