### ISSUE TITLE
(high) [Sign Language page] make "standards requirements" more encouraging

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#50]
> Most minimum accessibility standards do not require sign language; some do.

Which standards are you referring to, and which require sign language?

> Sign language is in the WCAG standard at Level AAA.

I suggest moving that first -- something like "Sign language is required by WCAG at Level AAA. It may be required by some policies and contracts, and is essential for many people with hearing disabilities" or such.

**Comment by shawna-slh** [comment]
Changed:
> Most minimum accessibility standards do not require sign language; some do.

to:
> Most minimum accessibility standards do not require sign language. It may be required by some policies and contracts.

In the [requirements](https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#Scenario_.2F_Use_Case_Examples), we have:
> _[advocate]_ I want to convince XYZ organization to make their media accessible. I want them to realize the importance for people with disabilities and the additional benefits that they get from it (e.g., SEO). **It'd be good if from skimming this resource they feel like it's not a huge task.** _(emphasis added)_

Realistically, most videos will not include sign languages. I think it's very important that readers get clear information that it's not an absolute requirements in most cases.

Shall we bring this to EOWG for discussion?

**Comment by nitedog** [comment]
I'm uncomfortable with "minimum standards".

How about something like this instead: "Sign language is not required by most policies. It is included in WCAG at Level AAA."

**Comment by shawna-slh** [comment]
Ok. I changed it to:

> Sign language is not required by most policies.

> Sign language is in the [WCAG standard](https://wai-media-guide.netlify.com/design-develop/media/planning/#standards) at Level AAA.
