### ISSUE TITLE
(medium) [Media Player page] listing comparisons

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#51]
I believe there have been other surveys/comparisons. What criteria are we using to list or not list studies/references?

**Comment by shawna-slh** [comment]
The one currently [linked in the Media Player page](https://wai-media-guide.netlify.com/design-develop/media/player/#existing-players) is the most vendor-neutral and comprehensive that I found. If anyone knows of other(s) that is more up-to-date &/or comprehensive and preferably not from a for-profit vendor, please do share!

Closing this issue as it's covered in https://github.com/w3c/wai-media-guide/issues/30
