### ISSUE TITLE
(medium) [Overall] confusing cross-links

### ISSUE THREAD

**Issue by nitedog** [w3c/wai-media-guide#52]
There are so many links in this resource and it is quite confusing which lead where (some go to external page, others to sub-pages in the resource, and yet others are in-page links).

**Comment by shawna-slh** [comment]
Yeah. **That's a challenge for usability**. _(I commented similarly on a non-WAI resource I reviewed recently :-)_

I've gone through and made it more clear in some places. It makes it more awkward but I guess probably worth it so readers know where links go. For example,<br>changed:

> WCAG includes requirements for audio and video media at [Level](https://www.w3.org/WAI/WCAG21/Understanding/conformance.html#levels) A, AA, and AAA.

to:

> WCAG includes requirements for audio and video media at Level A, AA, and AAA. (More info in a separate resource: [Understanding Levels of Conformance](https://www.w3.org/WAI/WCAG21/Understanding/conformance.html#levels).)

I'll keep working on it as I edit other pages.

**Comment by shawna-slh** [comment]
Note:
* Most in-page links should be indicated in text, e.g., "(WCAG is explained below.)"
* External links (off the W3C site) should have an icon at the end.
* Current WAI design is not to include an icon on any links that go to the W3C site including the WAI sub-side.

**Question for EOWG: Please share other ideas for:**
* Smoother ways to indicate where the links go.
* Specific places throughout the media resource where we should clarify where the link goes.

Thanks!

**Comment by hkramer** [comment]
I like the indication of the source of the resource. I'll leave it up to Shadi if this reduces the confusion from all the cross-links. It didn't bother me during my review.

**Comment by shawna-slh** [comment]
Thanks for the input, Howard. I edited a lot of them from the time Shadi commented until when you reviewed. Good to get your perspective that it works for you.

**Comment by Sylduch-Conseil** [comment]
> 
> 
> Yeah. **That's a challenge for usability**. _(I commented similarly on a non-WAI resource I reviewed recently :-)_
> 
> I've gone through and made it more clear in some places. It makes it more awkward but I guess probably worth it so readers know where links go. For example,
> changed:
> 
> > WCAG includes requirements for audio and video media at [Level](https://www.w3.org/WAI/WCAG21/Understanding/conformance.html#levels) A, AA, and AAA.
> 
> to:
> 
> > WCAG includes requirements for audio and video media at Level A, AA, and AAA. (More info in a separate resource: [Understanding Levels of Conformance](https://www.w3.org/WAI/WCAG21/Understanding/conformance.html#levels).)
> 
> I'll keep working on it as I edit other pages.

+1, sounds good. I have no opinion on the way it could be clearer with icons, but it may be worth a try.
