### ISSUE TITLE
[Planning] How to include Braille  in the resource

### ISSUE THREAD

**Issue by daniel-montalvo** [w3c/wai-media-guide#54]
First, this looks like a wonderful resource. Awesome work!

I have found several mentions/thoughts related to braille in the resource. For instance, in the Video Checklist and the "Provide Both Captions and a Transcript" section. 

It is certain that some people would prefer braille to read the captions (if they need them) or any other content, and in fact some screen readers provide this functionality already. VoiceOver lets you now decide if you want captions spoken by its speech engine, brailled, or both.

However, I think it doesn't help very much to connect a braille display directly to any computer / system without the screen reader's intervention. Whatever the format of the stream would be, it would first need to be suitable for the screen reader which would then parse it so that the user can choose between having the content spoken via the speech synthesizer, having it output through the braille display, or both.

Of course there are known issues at this point, mainly related to how users can handle the flow of text in smaller braille displays. Sometimes there is a lengthy piece of text that does not fit in a 18-20 cells braille display. Users might miss some of that text since they don't have time to reach to the end of the portion of text after new streams are sent to the braille display. These considerations are, however, out of scope for this resource.

So I would mention braille as a way in which users may read captions or transcripts. This is some useful information for people who might be in charge of shaping texts within captions or transcripts, but I would not get into details or specifics.

**Comment by shawna-slh** [comment]
You said:
> However, I think it doesn't help very much to connect a braille display directly to any computer / system without the screen reader's intervention.

Right. I know that and forgot that others don't. :-) In most places I added "available to screen readers for braille" to clarify that. Let me know if you think that clarification is needed anywhere else.

You said:
> It is certain that some people would prefer braille to read the captions (if they need them) or any other content, and in fact some screen readers provide this functionality already. VoiceOver lets you now decide if you want captions spoken by its speech engine, brailled, or both.

Cool! Does JAWS and NVDA?

I was under the assumption that most screen readers did not provide access to the captions. Would love to learn otherwise!

If common screen readers can access the captions, then audio without important visual information does not need a transcript -- right?
[Update: Transcript still needed for people who cannot process text at the speed of captions.]

I particularly want to understand and include what is needed to be accessible to people who are Deaf-blind. I opened a new issue specifically for that: https://github.com/w3c/wai-website/issues/567

**Comment by daniel-montalvo** [comment]
> You said:
> 
> > However, I think it doesn't help very much to connect a braille display directly to any computer / system without the screen reader's intervention.
> 
> Right. I know that and forgot that others don't. :-) In most places I added "available to screen readers for braille" to clarify that. Let me know if you think that clarification is needed anywhere else.
> 
> You said:
> 
> > It is certain that some people would prefer braille to read the captions (if they need them) or any other content, and in fact some screen readers provide this functionality already. VoiceOver lets you now decide if you want captions spoken by its speech engine, brailled, or both.
> 
> Cool! Does JAWS and NVDA?

No, they don't. There is not a setting like the Voice Over option I commented before. An experienced NVDA user could access subtitles for example in Youtube if they activate the subtitles checkbox and then press the up-arrow key until they get to the region of the page where subtitles populate. JAWS and Firefox users get the plus that they can hear the subtitles as they populate but braille focus doesn't follow the live text as it flows. This is not a good user experience, though.

> I was under the assumption that most screen readers did not provide access to the captions. Would love to learn otherwise!

The assumption that most screen readers don't provide access to captions would remain valid. I am only aware of the VoiceOver setting, for Android/Talkback I need to double check.

**Comment by shawna-slh** [comment]
Thanks for the additional info.

You said:
> The assumption that most screen readers don't provide access to captions would remain valid. I am only aware of the VoiceOver setting, for Android/Talkback I need to double check.

No need to check Android/Talkback. Since desktop screen readers don't feasibly, then we cannot count on it.
