### ISSUE TITLE
(for finalization) Layout improvements

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#55]
Planning: the video captions link is not using the [component for video links](https://w3c.github.io/wai-website-components/components/detail/video-links--inline.html) that indicates the video through a play button:

![IMG_4728](https://user-images.githubusercontent.com/58862/61456934-8e8f6a80-a967-11e9-8a41-4b529cfb89cd.PNG)

Planning: The table is not responsive. Tables are really hard to make responsive. The information provided is now also in the checklists at the top of the page, so maybe it is not needed here anymore (?).

![IMG_4730](https://user-images.githubusercontent.com/58862/61457069-d910e700-a967-11e9-8703-fdc6cb901496.PNG)

**Comment by shawna-slh** [comment]
> The information provided is now also in the checklists at the top of the page, so maybe it is not needed here anymore (?).

I think we need it in this form, still.
