### ISSUE TITLE
Pre-Recorded & Live Icons

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#56]
I have not been able to attend meetings in the past few weeks, but using a film clapperboard (I duckduckgoed that) for audio-only does not make a lot of sense to me. Likewise with the conversation bubbles for live.

I don’t have good ideas for icons here, tape would work for me, but maybe not as appropirate.

**Comment by shawna-slh** [comment]
Yup - those were just dummy icons for EOWG to confirm if we really wanted icons there.

The actual content/design of them is open in https://github.com/w3c/wai-website/issues/568
