### ISSUE TITLE
(strong) (overview) Understanding User Experiences/Needs

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#57]
Related to #26. 

I think this is too complicated as the introductory section on this page. It uses vocabulary that is jargon, like captions and transcripts before introducing them. This creates a feeling of being overwhelmed. 

The repetitiveness of “people who are/have” makes it hard to scan. I suggest shortening the bullet points, better describing the actual needs. I would also suggest to move this after the list of pages that currently follows.

> It’s easy to understand that a person who is Deaf can’t hear the audio, so you need to provide important audio information in another form.

I don’t think we need this sentence as it is the first example.

**Comment by shawna-slh** [comment]
> people who are/have” makes it hard to scan

Interesting. I would think it would make it easier to skim for most readers.

> suggest shortening the bullet points

shortened some.

> better describing the actual needs

like how?

> It uses vocabulary that is jargon, like captions and transcripts before introducing them.

introduced in new summary

/me thinks captions and transcripts not jargony -- but then, who am I to tell? :-)

> I don’t think we need this sentence as it is the first example.

Edited the sentence, but left it there, as I felt it was needed as an introduction to the first bullet.

**Comment by shawna-slh** [comment]
/me tried:

> ... intro... Many people who:
> * are Deaf can read text well. They get the audio information from transcripts or captions. Some cannot, and prefer sign language.
> * are hard of hearing like to listen to the audio to hear what they can, and have captions to fill in what they can’t hear adequately.
> * have difficulty processing auditory information also use captions. Many use transcripts so they can read at their own pace.
> * are blind can’t see videos. They use audio description of visual information to understand what’s going on visually.
> * are Deaf-blind use a screen reader and Braille to read descriptive transcripts that include the audio and visual information as text.
> * cannot focus and comprehend auditory or visual information when there are changing visuals. For most videos, they also need descriptive transcripts.
> * cannot use their hands and use voice recognitive software to operate their computer, including the media player. And people who are blind need the media player to work without a mouse.

but it doesn't fee right without the people in each :-/
