### ISSUE TITLE
(high) [Overview] How to make Audio and Video Accessible section

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#58]
#### First sentence

> This resource walks through understanding accessible media, whether you are outsourcing it or creating it in-house.

This sentence reads funny to me. “understanding creating accessible media”? I don’t know what this sentence is supposed to be saying exactly, but I feel it might be better to put it into the summary box at the top.

#### Icons

* Some are on the right, some are on the left. Scanning, I wonder if that means something. 
* They all have different visual weight, which I find distracting
* It’s hard to see where information starts and ends.
* Decide for one side, make sure they properly work in a responsive way.

#### Page listing

* The format of the page listing is confusing, sometimes the page name is at the end, sometimes at the beginning. 
* “Transcribing Audio to Text” is missing. (Probably due to draft reasons. :-))
* The pages repeat user needs/experiences again. I like it better here, because it feels more in context. (See #57.)
* The listing should be in a list, the explaining text could likely be shorter.

**Comment by shawna-slh** [comment]
This page does not a have a simple list of other pages in this resource.

At least two people like how the "How to Make Audio and Video Accessible" section presents the different types of information. [e.g.](https://github.com/w3c/wai-media-guide/issues/38):
> I like how you are listing out the pages that provide overall considerations ("Planning" and new "Audio and Video Content"), and pages that describe specific features ("Audio Description", "Captions", "Transcripts", and "Sign Language"). Then the page "Media Player" kind of startled me. [when the graphic was on the left] This is not really a feature but also an overall consideration, so why is it listed like that?

Let's see what EOWG says in the meeting tomorrow...

**Comment by yatil** [comment]
> This page does not a have a simple list of other pages in this resource.

I don't think that is apparent to users just visiting the site (instead of dissecting it).

> At least two people like how the "How to Make Audio and Video Accessible" section presents the different types of information. e.g.:
> 
> > I like how you are listing out the pages that provide overall considerations ("Planning" and new "Audio and Video Content"), and pages that describe specific features ("Audio Description", "Captions", "Transcripts", and "Sign Language"). Then the page "Media Player" kind of startled me. [when the graphic was on the left] This is not really a feature but also an overall consideration, so why is it listed like that?

Maybe subheadings or sublists can help with that. I found it confusing and hard to understand when I saw it. It certainly was not obvious for me.

**Comment by shawna-slh** [comment]
I think part of the reason is because the tutorial design is sooooo ingrained in you. :-)

After EOWG's input today, I made some changes that I think help quite a bit.

I tried for sub-headings, and haven't yet found the right ones.

+1 for making the AD, CC, transcripts, & sign items a list!

I'll keep thinking about more tweaks to help.
