### ISSUE TITLE
(medium) [Overview] Additional Benefits section

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#60]
I am uneasy with the separation of User Experiences (but only for people with disabilities) and Additional Benefits. It gives the impression that users with disabilities do not benefit from the “additional benefits”, but they often do.

I wonder if those benefits should alternatively not go to the respective pages as they are listed by feature anyway.

**Comment by shawna-slh** [comment]
> User Experiences

Changed to "User Needs" per  https://github.com/w3c/wai-media-guide/issues/26
(even though I really preferred "User Experiences" :-)

**Maybe that change helps with -- or even fully addresses -- your uneasiness?**

> It gives the impression that users with disabilities do not benefit from the “additional benefits”, but they often do.

**Most definitely the listed "Additional Benefits" also benefit people with disabilities!**

That section starts with **_"Accessible video and audio is essential for people with disabilities, and is useful for everyone in a variety of situations."_**

Do you have ideas for making it more clear that the additional benefits below apply to people with disabilities and people without disabilities?

> I wonder if those benefits should alternatively not go to the respective pages as they are listed by feature anyway.

Those pages are really focused on how to do it. And they're already very content heavy. I feel conceptually for the overall resource, they're good here. Also, EOWG already approved this organization. ;-)

**Comment by shawna-slh** [comment]
Maybe change "Additional Benefits" to "Benefits to People With and Without Disabilities" ?

Is that better or too cumbersome... I think I'll try it and see what EOWG thinks. :-)

**Comment by shawna-slh** [comment]
OK, I redid the section. Added benefits to orgs, and tried to clarify the benefits listed are for pwds and tabs.

I'm really happy about adding the benefits to orgs. And I hope the clarification is clear, because I agree that it is very important.

Thanks for spurring this change. :-)
