### ISSUE TITLE
(high-ish) [Planning] Merge introduction and summary

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#61]
The Introduction seems largely redundant to me. Especially the recap of the Overview page is unnecessary. I suggest merging with the summary and going into the (faux) meat of the topic immediately.

**Comment by shawna-slh** [comment]
I think this is useful/important for people who land on this page first, e.g., from a search engine:
> For background, see Making Video and Audio Accessible - Introduction that provides:

This is useful to help project managers put people first, not just checklist:
> examples of user experiences to help you understand...

I think this is not absolutely necessary / vital information. Yet, I think it helps managers realize that they have competing pressures.

> What accessibility features you provide with your media will likely be influenced by:
> * governmental regulations and other policy requirements
> * budget and time constraints
> * user needs

If you want EOWG to discuss this, feel free to re-open the issue.
