### ISSUE TITLE
(medium) [Planning] Project Management section

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#63]
* In have never heard of “Requests for Tender” before. (But that might be just me.)
* The workflow should have “Example” in the box title.
* I don’t find the workflow example very useful. I think knowing who is responsible is very interesting content, but the categories seem somehow too broad so that the responsibilities are quite nebulous.
* I don’t feel that the section gives readers a good way to determine if they have the skills for some of the accessibility features in-house or not.

**Comment by shawna-slh** [comment]
> In have never heard of “Requests for Tender” before. (But that might be just me.)

https://en.wikipedia.org/wiki/Request_for_tender

> The workflow should have “Example” in the box title.

done.

> I don’t feel that the section gives readers a good way to determine if they have the skills for some of the accessibility features in-house or not.

It's in the links:

> To help you plan in-house and outsourced work, the sub-pages of this resource include considerations, skills, and tools needed for creating accessible media in these sections:
> * Audio Description Considerations
> * Captions, Skills and Tools and Automatic Captions are Not Sufficient
> * Transcripts, Process - Skills and Tools
> * Media Players, Skills and Tools
> * Sign Languages, Skills and Tools

Let me knwo fi you have suggestions for making that more clear.

Thanks.
