### ISSUE TITLE
(medium) [Content] Overall structure

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#65]
* Use Description Lists (`<dl>`) instead of headings. Most content is rather short and does not need a lot of additional content. However, if I see a heading, I expect more in-depth content.

* For example in “Give people time to process information”, I would wonder about the length of each topic, how much time is appropriate. When would it be beneficial to split a video in two for self-pacing? I don’t think this page needs to give all this information (of which a lot is style or preference), but having a long table of content creates expectations.

* The plan for audio description of visual information on the other hand us very in-depth, but I wonder if this information should not be in context on the AD page. It feels unbalanced to the rest of the content of the page and makes AD feel overwhelming (compared to other content).

**Comment by shawna-slh** [comment]
For this page, I think it's particularly helpful to have the "Page Contents" list each point **along with who/when** (script, storyboarding, etc.)

This was done to address a comment from Estella (which I agree with).

It's also a bit like the [Tips pages contents](https://www.w3.org/WAI/tips/developing/) and the [Presentations Accessible headings](https://www.w3.org/WAI/teach-advocate/accessible-presentations/).

**Comment by shawna-slh** [comment]
> The plan for audio description of visual information on the other hand us very in-depth, but I wonder if this information should not be in context on the AD page. It feels unbalanced to the rest of the content of the page and makes AD feel overwhelming (compared to other content).

This page addresses what you can do with **new audio and video**.  I think it's important to have it here.

Lot of readers will have existing videos and won't be able to do anything about this information. Therefore, It would be irrelevant to them on the AD page.

I'll take another pass at the AD page and make sure the links and relationships are clear.

Yes, it is more complex than the other content on this page. That's just the nature of the information. :-)

**Comment by yatil** [comment]
> For this page, I think it's particularly helpful to have the "Page Contents" list each point along with who/when (script, storyboarding, etc.)
>
> This was done to address a comment from Estella (which I agree with).
>
> It's also a bit like the Tips pages contents and the Presentations Accessible headings.

I think those two pages actually neatly show my point. If you can scan the content itself quickly because it is compact, you don’t need everything in the TOC. So the Tips do it well, and the Presentations do not (which I have remarked upon).

I refrain from re-opening the issue because there seems to be consensus that this is the best way to do it.
