### ISSUE TITLE
(medium) [Audio Description] “Described video”

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#66]
I still (#5) feel quite strongly-ish that we should use “audio-described video” instead of just described video. The description of the visual video content is made through audio, and I think it is a significant aspect. Otherwise a video that has a transcript that include visuals might be confused with a described video.

**Comment by eoncins** [comment]
+1 audio-described video

**Comment by shawna-slh** [comment]
I reconsidered the overall terminology and consulted with others.<br>**Please read [Audio Description / Video Description / Described Video Terminology]( https://github.com/w3c/wai-media-guide/issues/75)**

> The description of the visual video content is made through audio, and I think it is a significant aspect.

Conceptually it could be provided as synchronized text, which probably many braille readers would prefer. But I know we're not there.

> Otherwise a video that has a transcript that include visuals might be confused with a described video.

I went through the entire resource and edited it to try to avoid that potential confusion. On the Audio Description of Visual Information page, I think it's clear from context. I checked that there's nothing about transcripts on that page.

On other pages, it doesn't use just "described video" and instead: "described version of the video" or other to make it clear that it is referring to a version of the video with additional audio description of visual information or a separate audio stream – not a descriptive transcript.

> use “audio-described video” instead of just described video

I re-considered this. Given the background and current draft of the page,<br>**I decided to try it**.

The first place "described video" shows up is the Page Contents – in long headings.
* "Creating a Separate Described Video - If Descriptions Fit in Spaces"
* "Creating a Separate Described Video - If Descriptions Do Not Fit in Spaces"

/me thinks: hummm, I'm really not keen on making those headings even longer

It's 4 times in the checklists:
* "…provide a separate described video."

And one other place (besides the Terminology section):
* "generate the new described video with the audio file that you just created."

Given the context of how "described video" is now used on the [Audio Description of Visual Information](https://wai-media-guide.netlify.com/design-develop/media/description/) page, it seems more cons than pros to changing it to “audio-described video”.

OK? Or more consideration and discussion needed?

**Comment by yatil** [comment]
> * "Creating a Separate Described Video - If Descriptions Fit in Spaces"
> * "Creating a Separate Described Video - If Descriptions Do Not Fit in Spaces"
>
> /me thinks: hummm, I'm really not keen on making those headings even longer

I remarked somewhere else that those headings might be better split into two levels of hierarchy, for length but also for scanning reasons:

* Creating a Separate Described Video
** Enough Space for Descriptions
** Not Enough Space for Descriptions

As for the repetitiveness, I think on the AD page, it would be ok to define it at the top and then use an abbreviation:

_brainstorming_

> … audio-described video (AD video) …

or even

> … audio-described video (ADV) …

Not feeling super-strongly about any of those particular suggestions, but maybe it is helpful as an input. :-)

**Comment by eoncins** [comment]
+1 to AD video
+ 1 NOT making those headings even longer 

Maybe use bold or capital for FIT and DO NOT FIT
"Creating a Separate Described Video - If Descriptions Fit in Spaces"
"Creating a Separate Described Video - If Descriptions Do Not Fit in Spaces"

**Comment by shawna-slh** [comment]
+1 to bolding "Creating a Separate Described Video - If Descriptions Do **Not** Fit in Spaces"

/me not sure about

> I remarked somewhere else that those headings might be better split into two levels of hierarchy, for length but also for scanning reasons:

> Creating a Separate Described Video
> ** Enough Space for Descriptions
> ** Not Enough Space for Descriptions

I might add a separate for issue for EOWG Comment.

**Comment by shawna-slh** [comment]
Thanks for quick reply. And suggestions that are not super-strong -- it's most helpful to get such suggestions. :-)

/me edits above from "See" to "**Please read**"

Based on [Audio Description / Video Description / Described Video Terminology]( https://github.com/w3c/wai-media-guide/issues/75), we want to ***de-emphasize* any use of "audio"** part, so that's counter to the idea of an abbreviation of "audio described".

@yatil & @eoncins - After reading [Audio Description / Video Description / Described Video Terminology]( https://github.com/w3c/wai-media-guide/issues/75), are you OK leaving it as is, or shall we bring it to EOWG for discussion?

**Comment by yatil** [comment]
> @yatil & @eoncins - After reading Audio Description / Video Description / Described Video Terminology, are you OK leaving it as is, or shall we bring it to EOWG for discussion?

OK for me

**Comment by shawna-slh** [comment]
https://github.com/w3c/wai-media-guide/issues/75#issuecomment-514730223

**Comment by shawna-slh** [comment]
> +1 to bolding "Creating a Separate Described Video - If Descriptions Do Not Fit in Spaces"

Actually, bolding won't do any good in the heading itself because it's already bold. :-)
Generally all-caps is to be avoided as some take it as shouting.
I made _not_ italic.
Hopefully that helps.

> I remarked somewhere else that those headings might be better split into two levels of hierarchy, for length but also for scanning reasons:

> Creating a Separate Described Video
> ** Enough Space for Descriptions
> ** Not Enough Space for Descriptions

> I might add a separate for issue for EOWG Comment.

I started an issue for EOWG comments -- and in reviewing the draft of it in the page, I decided against it for a few reasons, including size of heading and mostly because it actually added quite a bit of cognitive load to figure out the different options (even for me who knows what they say :-).
