### ISSUE TITLE
(medium) [Audio Description] 

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#67]
#### Audio Description Consideration, Skills, and Tools

* This section has no content about tools. It just says you need tools, but it does not communicate what the requirements for these tools are.
* I semi-strongly think that the information from [content] could fit better here. 
* I suggest removing the list and sentence before it.

#### What Description to Provide for My Video?

* Not a big fan of the heading, it is a weird phrasing. Either make it a complete sentence “What description do I need to provide for my video?” or something line “Providing Description for your video” (the pages use you sometimes, and here my (= I) and that is confusing).

* Also, the phrasing of the heading makes it look like there are different types of description, which might be ok, but for my understanding, audio description is the technique and then there are different approaches depending on the video material.

* Unclear bullet point:

  > * Space in audio — Is there enough space in the main audio for the description? That is, are there sufficient pauses throughout the narration or speaking where the relevant description will fit? For example,
   >   * If the only description needed is at the beginning of the video where these is a text title and background music, then: Yes, there is enough space.

  This seems like a very specific example – maybe this is to setup a scene and the rest is conversation/audible drama (“Peter and Mary are sitting ot a breakfast table, he looks at her, sceptically. The words ’A deadly breakfast‘ appear on the screen.”) If I didn’t know audio descriptions relatively well, I would probably not understand what this text means.

* Examples would be super useful. Short clips that demonstrate what is meant. An image says 1000 words, a video is 60 images per second! :-)

* Unsure if the boxes should not have checklist format.

* The Information seems to be provided in two steps, first the descriptions and then the two boxes. Maybe it could be simplified?

#### Options for Creating Description

* I don’t understand the decorative image. thinking about it for a long time the mountain is sound waves/bars on the right? For a icon that blocks reading (as it is left aligned), it should be either more significant or clearer.

* “If Descriptions (Do Not) Fit In Spaces” – Use sub headings instead of appendixes to the heading.
 
  * Especially as the first three steps are the same, I think there is some potential for simplification here.

#### Tips for doing Description Yourself

* This is good advice.

**Comment by shawna-slh** [comment]
per outside-github exchanges, closing this issue. addressing some points in other GitHub issues or directly.

**Comment by shawna-slh** [comment]
> This section has no content about tools. It just says you need tools, but it does not communicate what the requirements for these tools are.

Right. Details about the tools are out of scope. The purpose of this section is to broadly communicate the Scope of Work – to help decide whether to develop in-house or outsource. It's linked from https://wai-media-guide.netlify.com/design-develop/media/planning/#in-or-out – which links to similar sections in all the relevant sub-pages.

I wonder about changing those headings to something like: "For Planning - Skills and Tools"
?

**Comment by shawna-slh** [comment]
I made several more changes. I really do hope you find them helpful (even if compromise). e.g.:
> * What Method of Description?
> * Options for Creating Description
>    * Integrated — Creating Integrated Description
>    * Text — Creating Description in a Text File
>    * Audio Only — Creating Description in a Separate Audio File Only
>    * Video with Space — Creating a Separate Described Video - If Descriptions Fit in Audio Spaces
>    * Video Without Space — Creating a Separate Described Video - If Descriptions Do Not Fit in Audio Spaces
