### ISSUE TITLE
(medium) [Captions/Subtitles]

### ISSUE THREAD

**Issue by yatil** [w3c/wai-media-guide#68]
#### Captions and Subtitles

This is too much information. Many places call “captions and subtitles” subtitles, too. I think this could be simplified.

1. The heading should be Terminology.

2. Change the text to something like:
  
   > Subtitles is audio content that is shown as text alongside the visual content of a video. Some areas (mostly USA) call subtitles in the language of the video “captions”. In other areas “intralingual subtitles” are used in this case when a distinction is necessary. Subtitles (in a different language) are called “interlingual subtitles” in those cases. This resource uses the term “captions” throughout.

#### Live captions

I am pretty sure we don’t need to explain what “remotely“ means.

#### Captions for audio-only content?

I have never seen captions for audio content. Usually people use transcripts (that get updated in an ongoing way). I could see that for radio content or similar, but I cannot recall ever seeing captions for an audio-only source.

#### Skills and Tools

I think the skills and tools section makes it sound very hard to make captions, it is a skill that needs to be required, but especially for tools, the bar seems relatively low, especially with automatic captioning available to build on.

#### Other Options

The heading suggests that these are other options to providing captions, however it is just how captions are displayed. As the content of that section is pretty nebulous at best (what is the difference between “pop-on”, “roll-up”, “paint-on”??, I suggest removing the whole section, replacing it with a sentence in the summary that says “Captions can be displayed on the screen in different ways” or something.

**Comment by shawna-slh** [comment]
> [13:12] <yatil> FWIW, you don’t have to reply to my comments and can just close it. 

addressed as felt fit, mostly based on input from other EOWG participants
