### ISSUE TITLE
[later][coding] icons in headings & TOC

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#70]
We will probably want to use icons in a few headings and box titles. context: [Planning page](https://wai-media-guide.netlify.com/design-develop/media/planning/#top)

We probably do _not_ want the icons in the generated TOC (because they take too much attention away from the other items and look inconsistent) <-- yet to be confirmed.
UPDATE: current iteration does not include those headings in the TOC so don't need to do anyting about that for now anyway.

**Comment by yatil** [comment]
I think for consistency, having the icons in the TOC makes sense. We just need to make sure that when we use icons, we use them in a consistent way. (I also doubt that I or anyone can do anything against icons showing up in the TOC, apart from `display:none`-ing it in the page-specific CSS.)

**Comment by shawna-slh** [comment]
Since we don't need this in any resources now, and we have plenty of other thing to do, closing this issue!
