### ISSUE TITLE
Introduction: Benefits to Organizations and Individuals

### ISSUE THREAD

**Issue by Sylduch-Conseil** [w3c/wai-media-guide#76]
1. Ok with all benefits. But I suggest to change the order of benefits in beginning with humans and not search engines. 
Suggestion: put "Better indexing by search engines." at third place and not firts bullet.

2. Other point, may be a wor missing: "Benefits to organizations are illustrated these other resources:"
Illustrated IN these other resources"? 

3. Typo: public transporation instead of public transportion

**Comment by shawna-slh** [comment]
Thanks! Done.
