### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#8]
## Background

A fundamental question is "audio and video" &/or "media" in the title and throughout. Basically, many people will look for "audio and video". Yet some want "media" in the title ([Judy in survey](https://www.w3.org/2002/09/wbs/35532/Media-1-May-2019/results#xq3)).

**User experience optimization:** A strong recommendation from usability testing in late 2017 (thanks Visa!), was to have the navigation be "Make Audio & Video Accessible", and not "media" ([ref](https://github.com/w3c/wai-media-intro/issues/107)) – based on what users were looking for in the navigation to complete a task about captions. 

Common usage of "media" is broader than just audio and video.  For example, "print" is a type of media. "Media" is used differently in different contexts. Do a web search on "types of media" and you get lots of different perspectives.
"Multimedia" is often used to mean audio and video.

W3C documents often use "media" for audio and video, but not always. For example:
* WCAG uses "[time-based media]( https://www.w3.org/TR/WCAG21/#time-based-media)" and "[synchronized media](https://www.w3.org/TR/WCAG21/#dfn-synchronized-media)". (Previous EOWG comments were that "time-based media" is jargon.)
* [Media Accessibility User Requirements]( https://www.w3.org/TR/media-accessibility-reqs/) uses just "media" to mean audio and video.
* [Media Queries](https://www.w3.org/TR/css3-mediaqueries/) includes screen and print.
* …

<hr>

Perhaps the most technically correct and broadly recognizable phrasing is "**audio and video media**".  The [30 May draft](https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/) has that in the main title and navigation so you can see it in context.<br>_(Note that for people who use "media" to mean "audio and video", that would likely seem awkwardly redundant.)_

<hr>

A few things to keep in mind:
* This page is on the W3C WAI website which gives it some context (especially for the navigation short version).
* The full title hopefully will be referred to in places that might not include that context.
* The scope can be clarified in a subtitle &/or the summary &/or introduction.
* See [draft](https://deploy-preview-7--wai-media-guide.netlify.com/design-develop/media/) for what else is around it in the navigation.

<hr>

EOWG discussions:
* [31 May](https://www.w3.org/2019/05/31-eo-minutes.html#item03)
  * **"audiovisual media" common terminology in some areas** in Europe
  * includes discussion of "WAI" in title
* [26 April](https://www.w3.org/2019/04/26-eo-minutes.html#item05)

**Comment by shawna-slh** [comment]
_**[Everyone is encouraged to add your brainstorms to this comment!]**_

Brainstorms for full title and for short version in WAI website navigation:

* _full:_ How to Make Audio and Video Media Accessible<br>_nav:_ Make Audio and Video Media Accessible<br>_nav:_ Audio and Video Media<br>_full:_ How to Make Audio and Video Accessible<br>_full:_ How to Make Media (Audio and Video) Accessible<br>_full:_ How to Make Media on the Web Accessible

* _full:_ Making Audio and Video Accessible<br>_full:_ Making Audio and Video Media Accessible<br>_full:_ Making Media (Audio and Video) Accessible<br>_full:_ Make Media on the Web Accessible

* _full:_ WAI Media Guide: Making Audio and Video Accessible<br>_nav:_ Media Guide for Audio and Video<br>_full:_ WAI Guide: How to Make Audio and Video Media Accessible<br>_full:_ WAI Media Guide: Creating and delivering accessible audio and video content<br>_nav:_ Media (Audio and Video)<br>_full:_ Guide to Accessible Media for Web and Mobile<br>_full:_ Accessible Media Tutorial

* _full:_ Audiovisual Media – Make Audio and Video accessible<br>_full:_ Audiovisual Media – Making Audio and Video Accessible<br>_full:_ Audiovisual Media – How to Make Audio and Video Accessible
* _full:_ WAI Audiovisual Media Guide to Making Audio and Video Accessible<br>_full:_ WAI Audiovisual Media Guide: How to Make Audio and Video Accessible<br>_nav:_ Audio-Video Media

**Comment by bakkenb** [comment]
I like...
> _full:_  Making Audio and Video Media Accessible
> _nav:_  Media (Audio and Video)

**Comment by sharronrush** [comment]
My preference is for: Making Audio and Video Accessible 
2nd choice: How to Make Audio and Video Accessible

**Comment by daniel-montalvo** [comment]
My preferences are:
* full: How to Make Audio and Video Media Accessible
* Nav: Media (Audio and Video)

**Comment by cochfarf** [comment]
+1 to 
full: Making Audio and Video Media Accessible
nav: Media (Audio and Video)

**Comment by shawna-slh** [comment]
Based on various considerations and input, current version has:
full: **Making Audio and Video Media Accessible**
nav: **Audio & Video Media**

We'll go with that &mdash; unless/until someone wants to re-open the issue. :-)
