### ISSUE TITLE
Checkbox-like bullets

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#81]
On the Planning page, the [Checklists](https://wai-media-guide.netlify.com/design-develop/media/planning/#--video-checklists) have bullets that look a little like checkboxes.

Pro: Nicely communicates that you need to do those things.
Con: Might seem interactive to some.

EOWG - What ideas to do you have?<br>Leave them as is? Try _____  to make them look less click-able?<br>Change them to regular round bullets? Make them square bullets?<br>Other?

**Comment by hkramer** [comment]
I noticed this when viewing it on the last call. I think it breaks affordance. I would choose a bullet point that does not look like a checkbox - bullet or filled or unfilled circle, etc.

**Comment by yatil** [comment]
Not feeling strongly about this one. The safe thing to do would be to use normal bullets. (One idea could be just using checkmark icons ✓ for the must-have items, and ? or normal bullets for the nice to have’s, but that would probably need more deciphering for readers.)

**Comment by bakkenb** [comment]
When I first looked at the page I thought the same thing as Howard. If it is somewhat of a checklist for people to look through, and we don't want it to seem like the page is interactive, then I would suggest to use checkmarks as the bullets. That way it will be like a checklist, but not seem interactive as the checkmarks would serve as bullets in this case.

**Comment by shawna-slh** [comment]
Per EOWG telecon 26 July: Change them to not look like checkboxes, and to be different from the other round bullets.

**Comment by shawna-slh** [comment]
Eric updated the rest of the WAI website template to use standard filled-in bullets -- and these to use open circles.

**Comment by yatil** [comment]
> Eric updated the rest of the WAI website template to use standard filled-in bullets -- 

Confirm, I did that. 

> and these to use open circles.

I must have missed that… I’ll add a non-Standard style to our styleguide. (I don’t think that people will pick up the difference between billeted and circled list, and that’s probably ok in this case.)

**Comment by yatil** [comment]
You can now use the alt class on the list to invoke open circles: https://wai-website-theme.netlify.com/components/lists/#circle

**Comment by shawna-slh** [comment]
I had hacked the open circles and then forgot. ;_)
