### ISSUE TITLE
Things - allergy

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-media-guide#83]
Link: https://wai-media-guide.netlify.com/design-develop/media/#how-to-make-audio-and-video-accessible
Sentence: "When you are creating new audio or video, there are several **things** to consider such as background noise and avoiding flashing that can cause seizures. These are explained in Audio and Video Content."
Suggestion:  can we replace the word "things" with "elements" or "aspects" or anything else?
I don't feel terribly strongly about it but I am a little allergic to the word "things".

**Comment by shawna-slh** [comment]
he, he. I appreciate the mild allergy to "things".  I think here "elements" or "aspects" don't work.

I edited it to:

> When you are creating **new** audio or video, there are several accessibility barriers to avoid such as flashing that can cause seizures and distracting background noise. 

-- which I think is much stronger!

**Comment by vmmiller** [comment]
Perfect,
Thanks,
Vicki
