### ISSUE TITLE
Notes

### ISSUE THREAD

**Issue by a11ycob** [w3c/wai-media-guide#84]
# General feedback

## User needs intro

Possible revision:

> Before exploring specific media accessibility techniques, it is important to understand the needs of the users these techniques serve. While each outlined modality is beneficial for its defined user group, they are not limited to that group. For example, closed captions are a primary consideration for deaf or hard of hearing users but are also useful for people with cognitive challenges, and children learning to read.  

## Line item for audio description in User Needs section:

> People who are blind can’t see videos. They use audio description of visual information to understand what’s going on visually.

This is an absolute statement which is not always true. Blindness is a spectrum and many people who are legally blind have some form of vision.

Consider the following revision:

> Users who are blind and unable to consume visual elements within a video leverage audio descriptions. 

##  Line item for Deaf in User Needs section:

> People who are Deaf-blind use a screen reader and Braille to read descriptive transcripts that include the audio and visual information as text

Another absolute statement defining requirements of this user group.

Consider the following revision:

> Deaf-blind users may use a screen reader and/or refreshable braille display to read descriptive transcripts that capture audio and visual information as text

Finally, in this section:

> Some people cannot use their hands and use voice recognitive software to operate their computer...

I don't feel this is a necessary bullet point as it is not specific to media accessibility, but an overall accessibility requirement.

**Comment by shawna-slh** [comment]
Great to see that you've been able to make time to review this!

Responses below.

>> Some people cannot use their hands and use voice recognition software to operate their computer...

> I don't feel this is a necessary bullet point as it is not specific to media accessibility, but an overall accessibility requirement.

It applies to the media player, which is in scope for this resource:
> Some people cannot use their hands and use voice recognition software to operate their computer, including the media player. And people who are blind need the media player to work without a mouse.

**Comment by shawna-slh** [comment]
We are trying to keep the wording as simple as "plain language" as feasible. I do agree with some of your points about "not absolute". I wonder in this context how important some of those are? And how we can make needed tweaks without complicating the wording so much.

> People who are **blind** can’t see videos.

changed to:

> People who are totally **blind** can’t see videos.

**Comment by shawna-slh** [comment]
> > People who are Deaf-blind use a screen reader and braille to read descriptive transcripts that include the audio and visual information as text.

> Another absolute statement defining requirements of this user group.

Question for you: Is there any other way that a person who is Deaf-blind gets the content from videos?

**Comment by shawna-slh** [comment]
> User needs intro
> Possible revision:
> Before exploring specific media accessibility techniques, it is important to understand the needs of the users these techniques serve. While each outlined modality is beneficial for its defined user group, they are not limited to that group. For example, closed captions are a primary consideration for deaf or hard of hearing users but are also useful for people with cognitive challenges, and children learning to read.

We really want this section to focus on primary user needs, and not add the complexity of additional benefits. We have very long section lower in the page [Benefits to Organizations and Individuals](https://wai-media-guide.netlify.com/design-develop/media/#benefits-to-organizations-and-individuals) that is also linked at the top in the Page Contents. We made sure to clarify that that section includes "Use by People With and Without Disabilities".

**Comment by a11ycob** [comment]
> 
> 
> We are trying to keep the wording as simple as "plain language" as feasible. I do agree with some of your points about "not absolute". I wonder in this context how important some of those are? And how we can make needed tweaks without complicating the wording so much.
> 
> > People who are **blind** can’t see videos.
> 
> changed to:
> 
> > People who are totally **blind** can’t see videos.

Given that many people who are new to disability don't understand that disability, and vision loss specifically, is a spectrum, assuming that blind equates to no functional vision, I believe it's very important. Misunderstanding your audience leads to ineffective requirements gathering, and therefore the accessibility of the overall initiative.

Plain language should not trump accuracy, IMO.

**Comment by a11ycob** [comment]
> 
> 
> > > People who are Deaf-blind use a screen reader and braille to read descriptive transcripts that include the audio and visual information as text.
> 
> > Another absolute statement defining requirements of this user group.
> 
> Question for you: Is there any other way that a person who is Deaf-blind gets the content from videos?

Of course. Being deafblind does not mean you are completely deaf and blind. Each sensory impairment has it's own spectrum and the combination of the two can impact each person quite differently. Also, how a person acquires skills for dealing with their situation is dependent on whether it is a congenital condition or acquired later in life. 

Many of the techniques like descriptions, captions, sign language could be leveraged depending on the unique abilities of the person in this community,

**Comment by shawna-slh** [comment]
+1 for simple language **_and_** accuracy

>> People who are **blind** can’t see videos.

> changed to:

>> People who are totally **blind** can’t see videos.

You don't think "totally" makes it accurate?

I tried:

> People who are **blind** can’t see videos well.

but that would be very odd to readers who think of totally blind.

Could do something like:

> Some people who are **blind** or have low vision can't see videos well or at all.

I'm just not sure it's worth the added complexity.

<del>With "totally blind" the statement is accurate I think.</del>

UPDATE: I changed to:

> Some people who are blind or have low vision can't see videos well or at all.

(so we can close out this issue :-)

**Comment by shawna-slh** [comment]
> People who are Deaf-blind use a screen reader and braille to read descriptive transcripts that include the audio and visual information as text.

added "Some" to the beginning.
