### ISSUE TITLE
To AG Reviewers

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#87]
**[Draft for Review](https://wai-media-guide.netlify.com/design-develop/media/)**

Status:
* complete draft of all content ready for review
* images are drafty and in-progress ([images status](https://github.com/w3c/wai-website/issues/568))
* there are a few open issues -- e.g., [for EOWG comment](https://github.com/w3c/wai-media-guide/issues?q=is%3Aissue+is%3Aopen+label%3A%22for+EOWG+comment%22) <-- and we welcome your input on those, too
* this draft is **fairly** stable, yet we might have some edits based on review from others

We would especially like AG to review the following information directly related to WCAG requirements:
* [WCAG Standard](https://wai-media-guide.netlify.com/design-develop/media/planning/#wcag-standard)
* [Checklists for Audio and Video](https://wai-media-guide.netlify.com/design-develop/media/planning/#checklists-for-audio-and-video)
* [in description page](https://wai-media-guide.netlify.com/design-develop/media/description/#checklist)
* [in captions page](https://wai-media-guide.netlify.com/design-develop/media/captions/#checklist)
* [in transcripts page](https://wai-media-guide.netlify.com/design-develop/media/transcripts/#checklist)
* [in media player page](https://wai-media-guide.netlify.com/design-develop/media/player/#player-accessibility-functionality)
* [some small sections of Accessible Audio Content and Video Content](https://wai-media-guide.netlify.com/design-develop/media/av-content/)

If you have any significant comments, especially that need EOWG discussion, it would be very helpful to get those **by Tuesday 13 August**.

Your comments:
* **Please indicate each comment as high, medium, or low (e.g., [nitedog comments](https://github.com/w3c/wai-media-guide/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Anitedog))**
* If you have several wording changes, editor(Shawn) prefers GitHub Pull Requests for each, or the page with tracked changes in a document (contact Shawn for more info)
* Especially if there are points that we want to get more input on from EOWG, feel free to open new GitHub issues. **Please open a new GitHub issue for each point.** Thanks!
* If not using GitHub and sending comments via e-mail, please CC the publicly-archived list wai-eo-editors@w3.org as appropriate

Use cases and tasks are in [Requirements Analysis for media resource](https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#Requirements_Analysis).

Feel free to contact editor/Shawn if you want background on the decisions EOWG made, for example, on the title.

**Comment by shawna-slh** [comment]
For changes since call for AG review on 24 July and telecon agenda on 6 August, **see [History](https://www.w3.org/WAI/EO/wiki/Accessible_Media_Resource#History)**

**Comment by lauracarlson** [comment]
Hi Shawn,

Many thanks to you and EOWG! This will be a great and sorely needed resource. I have no substantial comments but noticed one minor typo on [Making Audio and Video Media Accessible](https://wai-media-guide.netlify.com/design-develop/media/):

"an described version"
should be:
"a described version"

Thanks again,
Laura

**Comment by shawna-slh** [comment]
Thanks very much for your review, Laura!
Fixed typo/wordo. :-)

**Comment by jasonjgw** [comment]
This is a very good draft. On the "transcripts" page, "A live steam" should be "stream".

There have also been issues raised recently in W3C contexts regarding the proper placement and treatment of captions in 360-degree video. It may be useful at least to note the problem, even if we don't have solid guidance to offer at this stage. (There is relevant research by the BBC that resulted in a published paper, but, so far as I am aware, no broad consensus on appropriate practices.)

**Comment by mbgower** [comment]
I'm going to start reviewing from start, so excuse me if my comments are addressed later in doc (and I will delete as that occurs)
### Understand User Needs section
I'd be inclined to mention users affected by autoplaying content here.
I'd also mention users needing keyboard operation, and how that enters into media player control.
You also haven't mentioned users who have difficulties being understood (due to accent, speech impediment, etc) benefitting from captions, nor the benefit to non-native speakers consuming captions, etc. 
There's is also potential benefit to users who don't understand a word (i.e., limited vocabulary), and with captions have the ability to look up the meaning from the caption. Or the same person being able to have a transcript transformed to simpler text.
Not suggesting this needs to be comprehensive, but in my experience several of these can be help make a compelling benefits case.

**Comment by mbgower** [comment]
Example video:
nitpick editorial -- just a lot of "described/description" words in one sentence.
> a described version of the video with description of visual information integrated in the main audio and description available as text

could be 
> a version of the video with description of visual information integrated in the main audio and description available as text

**Comment by slhenry** [comment]
@mbgower - please see e-mail I just sent

**Comment by mbgower** [comment]
Benefits to Organizations and Individuals section
There is inconsistency between your punctuation at end of bullets. See preceding section where there is NO terminal punctuation for any ("That page provides: ").
First three bullets have periods. Two of next three have periods.  The first three are not complete sentences and do not make sense as periods.  The next three (following "benefits to organizations") are sentences. There are a few ways to do this, but you should figure out what the w3c style is and keep consistent.

I find the first bullet in the benefits section could be tweaked. I think at one point maybe the bolded text "case study data" was the link? It's now "increase your market reach", which is not as explicit as the other 2 bullet's links. I also found "data from adding transcripts" to be a little odd. Maybe "data on the results of adding transcripts"?

**Comment by mbgower** [comment]
Typo: "Use by People With and Without Disabilities should be "Used by People With and Without Disabilities", I think

**Comment by mbgower** [comment]
Should braille be capitalized?

**Comment by slhenry** [comment]
**Mike** - please see e-mail I just sent. Thanks!

**Comment by mbgower** [comment]
Yes, @slhenry I just actually read the instructions and saw I should be doing a PR for these changes. Do you want me to pull these out?

**Comment by slhenry** [comment]
> Yes, @slhenry I just actually read the instructions and saw I should be doing a PR for these changes. Do you want me to pull these out?

Yes, thanks.

**Comment by shawna-slh** [comment]
@jasonjgw said:

> This is a very good draft. On the "transcripts" page, "A live steam" should be "stream".

Fixed, thanks. (although "a live steam" might be great for those who like saunas ;-)

> There have also been issues raised recently in W3C contexts regarding the proper placement and treatment of captions in 360-degree video. It may be useful at least to note the problem, even if we don't have solid guidance to offer at this stage. (There is relevant research by the BBC that resulted in a published paper, but, so far as I am aware, no broad consensus on appropriate practices.)

Right. Maybe the best option is to allow users to set preferences. For example, with one player, users can position captions below the video. Anyway, this resource isn't providing such specific guidance on captions position and format. It's also not covering newer issues that don't have established solutions.

I did update [Positioning and Styling Captions](https://wai-media-guide.netlify.com/design-develop/media/captions/#positioning-and-styling-captions).

**Comment by jasonjgw** [comment]
I also noticed that the process of generating captions/descriptions/transcript from an already scripted video wasn't directly addressed. If this is common enough to mention, even a sentence or two would be valuable, as this mode of working should at least save some portion of the accessibility effort. Screenplays are the obvious example, but not the only kind of case.

**Comment by allanj-uaag** [comment]
Hi Shawn,
in the media player section
"Accessible media players provide a user interface that works without a mouse, through speech interface, when the page is zoomed larger, and **by screen reader users**." 
you call out screen reader users. perhaps say **with screen readers**
in Player Functionality
the controls need to have sufficient contrast. Many of the native browser players have poor contrast on controls. 
in other parts of the media guide you mention multiple caption tracks. It should be a function of the player to not only turn captions on and off, but also select from all caption tracks available. Same for description.

**Comment by jpascalides** [comment]
Hi Shawn, one minor suggestion regarding the section "Understand User Needs". 

It would be helpful to include a statement to the effect of: "Some individuals might prefer to use one or more accessibility features simultaneously to access content." This will help to ensure that the audience of this document understands that an individual may use one or more methods of accessing information. For example, an individual who is deaf might prefer sign language as their primary method of accessing content supplemented by captions or transcripts.

**Comment by shawna-slh** [comment]
Thanks for the review and comments, @allanj-uaag !

I revised this section: https://wai-media-guide.netlify.com/design-develop/media/player/#player-accessibility-functionality

> "Accessible media players provide a user interface that works without a mouse, through speech interface, when the page is zoomed larger, and by screen reader users."
> you call out screen reader users. perhaps say with screen readers

done.

> in Player Functionality
> the controls need to have sufficient contrast. Many of the native browser players have poor contrast on controls.

done.

> in other parts of the media guide you mention multiple caption tracks. It should be a function of the player to not only turn captions on and off, but also select from all caption tracks available. Same for description.

For now we're not listing every aspect of media player accessibility. We point to MAUR:
> More details on player accessibility functionality are in a separate document: [Media Accessibility User Requirements](https://www.w3.org/TR/media-accessibility-reqs/).

(In the future, perhaps WAI will be able to provide an updated listing of player functionality (e.g., http://kensgists.github.io/apt/ )

I'm inclined to not list this detail -- partly because I think most common players do let users select from multiple captions/subtitles and because the Description page of this resource addresses player functionality for description.

I'm open to being talked into it if you are so compelled. :-)

**Comment by shawna-slh** [comment]
@jasonjgw  wrote:
> I also noticed that the process of generating captions/descriptions/transcript from an already scripted video wasn't directly addressed. If this is common enough to mention, even a sentence or two would be valuable, as this mode of working should at least save some portion of the accessibility effort. Screenplays are the obvious example, but not the only kind of case.

Ah, right. I would think that would be obvious – yet, we wouldn’t want people to miss it. I added to the Introduction of  [Transcribing Audio to Text](https://wai-media-guide.netlify.com/design-develop/media/transcribing/):

> In some cases, there is already text available in a script. You'll probably need to make some minor edits so it's accurate with the final audio content.

**Comment by shawna-slh** [comment]
@jpascalides said:
> Hi Shawn, one minor suggestion regarding the section "Understand User Needs ".
> It would be helpful to include a statement to the effect of: "Some individuals might prefer to use one or more accessibility features simultaneously to access content." This will help to ensure that the audience of this document understands that an individual may use one or more methods of accessing information. For example, an individual who is deaf might prefer sign language as their primary method of accessing content supplemented by captions or transcripts.

Right. We have that idea in some places. For example in the [Sign Languages page](https://wai-media-guide.netlify.com/design-develop/media/sign-languages/):
> Some people will want to have sign language and captions at the same time.

I kinda don't want to repeat that example in the "Understand User Needs" section. For now, I added to the "Understand User Needs" section:
> Some people use multiple accessibility features simultaneously. For example, someone might want captions, description of visual information as text, and description in audio.

I mildly feel that this is too much…
(that section is already very long)
