### ISSUE TITLE
[sign languages] explain why not required?

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-media-guide#88]
From [Sylvie e-mail](https://lists.w3.org/Archives/Public/wai-eo-editors/2019Aug/0013.html):

In [Sign languages page](https://wai-media-guide.netlify.com/design-develop/media/sign-languages/): 
> Sign language is not required by most policies.
> Sign language is in the WCAG standard at Level AAA. 

Shouldn't it be explained why it is not required. Often, deaf people are not satisfied that sign language is not available.

**Comment by shawna-slh** [comment]
Good question.

My initial reaction is that explaining why it's not required in policies is beyond the scope of this resource. This resource is to tell people what they need to do and give them guidance on how to do it.

I think we would not want to explain why it is not required in policies anyway -- we generally stay away from such commenting in resources such as this. At most, we **might** try to explain why it's at AAA in WCAG. But even that I think is "a can of worms" and not in scope for this resource.

And, I'm open to other ideas.

**Comment by daniel-montalvo** [comment]
+1 to not going that far. I think it is important to keep outreach and standards separate, the audience, ton, and approach is different.

Moreover, the need of sign language (and the fact that some deaf people do not understand sign language) are well covered in the introduction.

> Sign language is the native language of many people who are Deaf. Some do not read or understand written language well &mdash; especially at the speed of most captions.
