### ISSUE TITLE
Not a sentence

### ISSUE THREAD

**Issue by awkawk** [w3c/wai-media-guide#91]
"And people who are blind need the media player to work without a mouse."

Last line of user needs section.

**Comment by shawna-slh** [comment]
In context [First, Understand User Needs](https://wai-media-guide.netlify.com/design-develop/media/#first-understand-user-needs)

> ...
> * Some people cannot use their hands and use **voice recognition software** to operate their computer, including the **media player**. And people who are **blind** need the media player to work without a mouse.

<hr>

Do you really want to get into this with a writer? ;-)

"People who are blind need the media player to work without a mouse." is a proper sentence.

Most grammarians say it's OK to start a sentence with "And", e.g., [1](https://www.merriam-webster.com/words-at-play/words-to-not-begin-sentences-with), [2](http://www.thewriter.com/what-we-think/style-guide/and-and-but-why-its-okay-to-start-a-sentence-with-a-conjunction/), ...

I think the "And" helps tie the idea with the previous sentence... And, I am willing to delete the "And" at the beginning if it **really, really** bugs you or others. :-)

**Comment by shawna-slh** [comment]
feel free to re-open this issue if you want it re-considered.
