### ISSUE TITLE
[!!] Edits

### ISSUE THREAD

**Issue by lakeen** [w3c/wai-media-guide#98]
[!!] Remove:  Under "How to Make Audio and Video Accessible"     **[](/design-develop/media/player/**

[!!] Some benefits of captions are illustrated in a 1-minute **Video on Captions**. (linking to Color Contrast video not captions video)

**Comment by yatil** [comment]
> [!!] Remove:  Under "How to Make Audio and Video Accessible"     **[](/design-develop/media/player/**

I’ve seen this and fixed that typo in https://github.com/w3c/wai-media-guide/commit/7e293c5689bb8eefb4f222e6c3abacbfba587bf5.

**Comment by shawna-slh** [comment]
Thanks for catching these, Laura!

> [!!] Some benefits of captions are illustrated in a 1-minute Video on Captions. (linking to Color Contrast video not captions video)

fixed in https://github.com/w3c/wai-media-guide/commit/10baf6569816a5907a13d64a403be5126500b379#diff-d680e8a854a7cbad6d490c445cba2eba
